### ISSUE TITLE
CMO: Handle Prepare Shipment button click action

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#107]
When an order is approved, the CMO will see a button **Prepare Shipment** on the **View Order** page.
Once the CMO clicks the button, a new entry will be added in the shipments database.  
See 2.1.1.
> Shipment entity inherits all attributes from 1.1-1 & Documents from 1.2-1, except order statuses and order comments

![1_CMO_Order_Prepare_Shipment-27](https://user-images.githubusercontent.com/1469129/129701231-f78f11fc-5c92-4274-8577-bcc2903c7822.jpg)

**Comment by abhayprasadnovartis** [comment]
Started working on this enhancement

**Comment by abhayprasadnovartis** [comment]
Created Pull request for this.

**Comment by Mastaleru** [comment]
Please see https://github.com/PharmaLedger-IMI/csc-workspace-main/issues/122#issuecomment-908315934
