### ISSUE TITLE
CMO: Implement Shipments Dashboard

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#122]
Query all the shipments stored in database and display them as indicated in mockups:

The table should support pagination and filtering

![1_CMO_Dashboard-Shipments-01](https://user-images.githubusercontent.com/1469129/130049026-0eb891aa-d3c5-4e19-a7d0-9abf788c7015.jpg)

**Comment by arijitnv** [comment]
I am currently working on this request.

**Comment by Mastaleru** [comment]
I cannot see order details in the shipments dashboard.

![image](https://user-images.githubusercontent.com/1469129/131341344-3580fc98-20fa-42ab-bb1c-496d973f5b27.png)

**Comment by Mastaleru** [comment]
I saw that that shipment model in the `createShipment`  method is inheriting the `order `properites, but the wrong properties are used. For example `sponsor_id `should be `sponsorId`, `study_id `should be `studyId`. I am expecting an explanation for this usage.

**Comment by klivit** [comment]
Duplicating #123?
