### ISSUE TITLE
SITE: Implement Shipments Dashboard 

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#123]
Query all the shipments stored in database and display them as indicated in mockups:

The table should support pagination and filtering

![1_SITE_Dashboard-Shipments-01](https://user-images.githubusercontent.com/1469129/130049260-a24b0dd1-5597-4a47-9779-87bfb8b48589.jpg)

**Comment by klivit** [comment]
I opened a separate issue (#231) regarding the filtering.
