### ISSUE TITLE
Order Details: Status Date time should be the last modified order date time

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#143]
Please check highlighted sections on the print screen.

<img width="1271" alt="Screenshot 2021-08-28 at 11 34 16 PM" src="https://user-images.githubusercontent.com/77613409/131254500-83c64181-6201-451c-a6d8-e627322d71a6.png">

**Comment by abhayprasadnovartis** [comment]
Started working on this bug

**Comment by abhayprasadnovartis** [comment]
Created Pull request for this.
