### ISSUE TITLE
Notifications: Missing notification when order initiated

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#144]
Notifications (partly) are missing. For example (see print screen), two orders were initiated, but only one notification was received (waiting time about 45 min). 

<img width="1275" alt="Screenshot 2021-08-28 at 11 31 28 PM" src="https://user-images.githubusercontent.com/77613409/131254559-27ce25d0-1ca1-46df-b7e6-68450e626c24.png">

**Comment by Mastaleru** [comment]
@klivit did you first created the orders and after that you opened the cmo app? it is important to know if you did so, because it might be a problem from issue #22

**Comment by Mastaleru** [comment]
The problem occurs because the generation of notification id is based on the existing notification length;
