### ISSUE TITLE
Getting Uncaught Errors every time Order changes the Status

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#145]
Please see an example below.

<img width="1293" alt="Screenshot 2021-08-28 at 10 43 39 PM" src="https://user-images.githubusercontent.com/77613409/131254725-4df0ba3c-a78c-47d8-b9b5-428b5dc88d1e.png">

**Comment by Mastaleru** [comment]
It should be solved from #22.
