### ISSUE TITLE
Notifications: Timestamps are not adjusted to the local (browser) time

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#146]
Please see an example below.

<img width="1288" alt="Screenshot 2021-08-29 at 5 55 14 PM" src="https://user-images.githubusercontent.com/77613409/131254862-e5f843bc-f7af-4192-9871-a582102b33af.png">

**Comment by abhayprasadnovartis** [comment]
Started working on this issue

**Comment by abhayprasadnovartis** [comment]
Create PR for this
