### ISSUE TITLE
SPONSOR, CMO: Change of the title in Wizard

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#147]
Please change "Confirmation" to "Summary".

<img width="1029" alt="Screenshot 2021-08-29 at 5 10 22 PM" src="https://user-images.githubusercontent.com/77613409/131255095-b97ae97a-20a6-4157-95df-e3688fdcde71.png">

**Comment by abhayprasadnovartis** [comment]
Started working on this

**Comment by abhayprasadnovartis** [comment]
Created PR for this
