### ISSUE TITLE
CMO: Cannot Submit Review

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#148]
After selecting "Submit Review" and confirming the submission, the system does not respond. Please see attached. All fields required to be filled by the CMO are fulfilled (e.g., comment, file attached).

<img width="1421" alt="Screenshot 2021-08-29 at 7 44 54 PM" src="https://user-images.githubusercontent.com/77613409/131258488-04d2cf1f-1bfc-4595-b4f3-92a324e38495.png">

**Comment by klivit** [comment]
I noticed that periodically the functionality works, meaning I can submit the review by the CMO. However, as I've attached the print screen, it does not work all the time.

**Comment by Mastaleru** [comment]
review process will be removed from the flow
