### ISSUE TITLE
Epic 1 DSUs Architecture validation

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#15]
DSUs architrecture diagram for a better understaing:
![Epic 1 DSUs architecture](https://user-images.githubusercontent.com/1469129/126766277-26e680b8-e6ea-4ee0-a018-e503d585f2e8.png)

Editing and commenting is possible here:
https://docs.google.com/drawings/d/1-R_bMrty5t0yPg0IQ7YZ_GCwGADs0wh3-8SVf0RXC34/edit?usp=sharing

**Comment by klivit** [comment]
The diagram was updated to reflect the changes 

![Epic 1 DSUs architecture-2](https://user-images.githubusercontent.com/77613409/127307281-65e0ce0d-e933-4240-8223-e0c9c5b734d3.png)
