### ISSUE TITLE
View History: Modify titles, add IDs, add functionality to redirect to other entities

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#150]
Please take into account the following notes:

1 -- It should be "Order" and "Shipment" as on the print screen (not "Orders" and "Shipments").

2 -- Order and Shipment have to include the ID of the entities (see print screen).

3 -- The User has to be given the functionality to be directed to (1) Order (View Order), (2) Shipment (View Shipment), (3) Kits (View Kits) [in Kits Dashboar].
If the User is accessing the History from the Order, the functionality given is: (2), (3).
If the User is accessing the History from the Shipment, the functionality given is: (1), (3).
If the User is accessing the History from any of the Kits, the functionality given is: (1), (2), (3).

![Screenshot 2021-08-30 at 1 05 16 PM](https://user-images.githubusercontent.com/77613409/131337522-6b5c3b06-4be2-4660-8467-b11b7b981b10.png)

**Comment by klivit** [comment]
Note
In case Shipment is not available yet (e.g., Epic 1, the Order just initiated), the "View Shipment" button should be muted.
In case Kits are not available yet (e.g., Epic 2, the Shipment is In Preparation), the "View Kits" button should be muted.

**Comment by Mastaleru** [comment]
> Note
> In case Shipment is not available yet (e.g., Epic 1, the Order just initiated), the "View Shipment" button should be muted.
> In case Kits are not available yet (e.g., Epic 2, the Shipment is In Preparation), the "View Kits" button should be muted.

I rather propose to don't show columns Shipment and Kits at all if them are not yet available

**Comment by klivit** [comment]
Agree.

**Comment by klivit** [comment]
List of corresponding specifications:
CSC-0-22	 
CSC-0-23	 
CSC-0-24	 
CSC-0-25	 
CSC-0-26	 
CSC-0-27	 
CSC-0-28

**Comment by Mastaleru** [comment]
For the Epic 1 should be implemented the notes 1 & 2
