### ISSUE TITLE
CMO: Implement View Shipment button on order page

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#152]
When an order has already a Shipment created a **View Shipment**  button should be available. Otherwise the user can create multiple shipments from the same order.

![image](https://user-images.githubusercontent.com/1469129/131351568-46360a65-c05a-4e05-87a8-8ea49d60b296.png)

**Comment by Mastaleru** [comment]
@klivit it is ok that the order could inherit the shipment status?

**Comment by klivit** [comment]
> @klivit it is ok that the order could inherit the shipment status?

Originally, the "In Preparation" status was assigned to the Order (as you propose). During one of the meetings, where we presented the mockups, the point was that it would be more logical and better to move it to Epic 2 and entitle Shipment with this Status, giving better clarity of the physical preparation of the Shipment.

We have another tricky element: Shipment is created without the shipment ID as, again, was clarified during one of the mockup demos; the Courier gives the shipment code. But the Courier is getting in the flow later.

This discussion brings me to the first approach we had, where Order can be "In preparation" and "Ready for Dispatch", and this all is part of Epic 1. The Epic 2 can start from the Shipment being added by the Courier, and some of the elements will be inherited from the Order.

P.S. The idea was that Shipment inherits the Order ID until it is given its Shipment ID (added by the Courier).
