### ISSUE TITLE
Add Kit ID List file upload

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#16]
KitIDs are needed in Epic 1 in order to proper save the order details.
@klivit please provide us an example of this file. Please keep in mind that for this stage of MVP we can use text files as *.json or *.csv in order to speed up the development. Usage of  *.xls files will force us to use external libraries.

**Comment by Desouler** [comment]
Created the component to load and read csv file assuming comma separated values. Will change in the future, but for now we can continue with Kit Ids DSU
