### ISSUE TITLE
[SPO, CMO, SITE] - OrdersDashboard - Last Modified date and time should be the status date

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#170]
Now the Last Modified column is the same as Request Date

![image](https://user-images.githubusercontent.com/1469129/131838085-6da618a8-cf48-4812-89fb-a67292bd59d9.png)

**Comment by Mastaleru** [comment]
Please get rid of _lastModified_ property from the order model

**Comment by klivit** [comment]
The issue remains. Please see the print screen. The true time of cancelation was 15:48. 

<img width="993" alt="Screenshot 2021-09-07 at 3 49 15 PM" src="https://user-images.githubusercontent.com/77613409/132347615-6e52304e-7f82-4d4b-b36c-9233ac6a3786.png">

**Comment by klivit** [comment]
The issue is fixed.
