### ISSUE TITLE
[CMO,SPONSOR] Remove delete buttons from "View Order"

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#180]
They are not functional but them should not be visible there.
Also, please remove the _Delete_ from table header.
![delete_cmo](https://user-images.githubusercontent.com/1469129/131958909-b046b6ce-2f08-4399-8ffc-ad2809ceab8c.jpg)
![delete_sponsor](https://user-images.githubusercontent.com/1469129/131958897-bf119274-4510-4c8e-a4f4-69fac8c62287.jpg)

**Comment by abhayprasadnovartis** [comment]
Started working on this issue

**Comment by abhayprasadnovartis** [comment]
Created Pull request for this

**Comment by klivit** [comment]
The issue remains.

**Comment by klivit** [comment]
The issue is fixed.
