### ISSUE TITLE
[SPO] Change temperature inputs from free text to number types

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#182]
On the "New Order page" add number types for temperatures inputs
Min Temperature and Max Temperature should be in range [-100, 100 °C].

Please assure that Min Temperature is always <=Max Temperature while the inputs change.

**Comment by abhayprasadnovartis** [comment]
Started working on this issue

**Comment by abhayprasadnovartis** [comment]
Created PR for this

**Comment by klivit** [comment]
@Mastaleru Reopened?
