### ISSUE TITLE
[SPONSOR, CMO] Should not receive a notification when they creates/reviews/approves/cancel/etc. an order

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#184]
Sponsor should receive notifications only when orders are reviewed by CMO.

**Comment by klivit** [comment]
The issue remains. Please see the print screen. 

<img width="1249" alt="Screenshot 2021-09-07 at 3 14 02 PM" src="https://user-images.githubusercontent.com/77613409/132342833-c9633cf6-61c8-4d73-b716-dd906f9468ad.png">
