### ISSUE TITLE
[SPONSOR] Cancel Changes button behavior change

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#192]
1. The button handler should prompt a modal that will inform user that all input data will be cleared.
2. What happens next? You should not submit an empty order.
I propose a message in the modal : "All entered data will be cleared and you will start over with Order Details"

Pressing the confirmation button clears the forms and will move user to step "1 - Order Details"

**Comment by Mastaleru** [comment]
@klivit what are your thoughts on this?

**Comment by Mastaleru** [comment]
I think this should apply to the review process

**Comment by klivit** [comment]
Generally speaking, I agree that the user needs to be notified when their action will lead to changes such as status change, clearing the forms, etc. 

This action is valid for both, Sponsor and CMO.

Before clearing the form, the confirmation message might be as follows: "All newly entered data will be removed. This will require you to start over the process of entering the details again."

**Comment by abhayprasadnovartis** [comment]
Started working on this

**Comment by abhayprasadnovartis** [comment]
Cleared all the forms now. Created PR for this
