### ISSUE TITLE
Notifications order does not show the most recent ones.

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#195]
The first notification (Order [dfgdfg]: Canceled t345	Sponsor	06-Sep-2021, 19:28)  was the latest added (I changed the computer clock- it was 20:28) in order to see if it is any lexicographic order.

![image](https://user-images.githubusercontent.com/1469129/132249308-2c7ebf04-4abb-4b19-8dc7-cafd90125ad2.png)

The desired behavior is: recent notifications should be shown first.

**Comment by abhayprasadnovartis** [comment]
Started working on this

**Comment by abhayprasadnovartis** [comment]
Created PR for this
