### ISSUE TITLE
[SPONSOR] Update View Shipment page after the status is set to Ready for Dispatch

### ISSUE THREAD

**Issue by paiusCatalin** [PharmaLedger-IMI/csc-workspace-main#215]
After the tasks #60, #61 and #65 are completed, update the View Shipment page for SPONSOR with all the available information according to the mockups.

![SPONSOR_Shipment-Ready-06](https://user-images.githubusercontent.com/17168446/132701317-3105fb01-572d-4089-998f-3e0f14791a2a.jpg)
![SPONSOR_Shipment-Ready-07](https://user-images.githubusercontent.com/17168446/132701321-312e23ab-56d9-44e4-80de-d6896fe3e676.jpg)
![SPONSOR_Shipment-Ready-08](https://user-images.githubusercontent.com/17168446/132701322-84daa841-3437-40a0-ba3e-dce02acbbdf8.jpg)

**Comment by paiusCatalin** [comment]
@klivit what kind of attached documents should we keep/show here? From my understanding there are some shipmentDocuments which will be added later when the shipment will be "In transit".

**Comment by klivit** [comment]
Kits' details are not available. 

<img width="1191" alt="Screenshot 2021-09-20 at 1 36 04 AM" src="https://user-images.githubusercontent.com/77613409/133945206-13a07cda-d167-4950-82d3-13d5a234aba0.png">
