### ISSUE TITLE
[SITE] Update View Shipment page after the shipment has the status In Transit

### ISSUE THREAD

**Issue by paiusCatalin** [PharmaLedger-IMI/csc-workspace-main#225]
![SITE_Shipment_In-Transit-08](https://user-images.githubusercontent.com/17168446/132862391-95ace070-d994-4d7e-a176-8a940e8c1d80.jpg)

**Comment by Mastaleru** [comment]
KitIdDSU is not available as described in #315

**Comment by klivit** [comment]
Related issue #350
