### ISSUE TITLE
[SPONSOR] Update View Shipment page with the new information after the shipment has been confirmed as Received by SITE

### ISSUE THREAD

**Issue by paiusCatalin** [PharmaLedger-IMI/csc-workspace-main#229]
![SPONSOR_Shipment_Received-15](https://user-images.githubusercontent.com/17168446/132863253-df0c0126-387d-48ba-b392-beccb5496964.jpg)
![SPONSOR_Shipment_Received-16](https://user-images.githubusercontent.com/17168446/132863255-1f6e3007-c323-4d72-9195-cb00b42af93a.jpg)
![SPONSOR_Shipment_Received-17](https://user-images.githubusercontent.com/17168446/132863249-2f0eee1a-603e-429c-b5a9-14f621659b15.jpg)

**Comment by Mastaleru** [comment]
Check that this is fully satisfied by #388
