### ISSUE TITLE
[CMO, SPONSOR] Wrong Site Id on orders dashboard

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#241]
It should be Site ID 1, Site ID 2 or Site ID 3. Don't use the array indexes for the options value.

![site-id](https://user-images.githubusercontent.com/1469129/133109604-901db0f4-b91c-4c66-b7f9-166b4a3ee70f.png)

**Comment by abhayprasadnovartis** [comment]
Started working on it

**Comment by abhayprasadnovartis** [comment]
Created PR for this
