### ISSUE TITLE
An error is displayed in the console when the user navigates from Orders Dashboard to other Dashboard

### ISSUE THREAD

**Issue by paiusCatalin** [PharmaLedger-IMI/csc-workspace-main#245]
**Error: Expression "ordersListNotEmpty" is not defined** - is displayed in the console when the user navigates from Orders Dashboard to other Dashboard. The same error is displayed when the user navigates back to Orders Dashboard

![image](https://user-images.githubusercontent.com/17168446/133242904-9a2dabbf-2e21-42d4-bd87-6c9da8f474e4.png)

**Comment by Mastaleru** [comment]
Fixed in WebCardinal but the effect will be seen in the future while now there are some new integration between webcardinal and opendsu
