### ISSUE TITLE
[CMO, Courier] Shipment status "In Preparation" should not be sent to Courier

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#249]
Now, the Courier can see the "In Preparation" status
![image](https://user-images.githubusercontent.com/1469129/133266166-620a830e-97af-4462-9be1-e610d0409988.png)

**Comment by arijitnv** [comment]
I am working on this issue. I am facing some issue in the Scan Shipment part and I am working with Kshitij for that. Once the scan shipment part is completed, I will be able to replicate this flow and will be able to do further enhancement.

**Comment by arijitnv** [comment]
I have implemented the changes but not able to raise PR because the old PR is not yet approved.
