### ISSUE TITLE
[SPONSOR] On Summary tab, Target CMO ID is the select value number instead of the CMO ID

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#253]
![image](https://user-images.githubusercontent.com/1469129/133283823-c8eeb5ca-078d-4053-a85d-bf026a0b3d15.png)

Please consider the same approach as in #252

**Comment by abhayprasadnovartis** [comment]
Started working on this

**Comment by abhayprasadnovartis** [comment]
Created PR for this
