### ISSUE TITLE
[CMO]: After the list of kits is successfully completed, the summary has a blank page

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#261]
<img width="1287" alt="Screenshot 2021-09-16 at 3 24 21 PM" src="https://user-images.githubusercontent.com/77613409/133611961-b3cc1b4f-0741-49bd-ab5d-afbc7cae8922.png">

**Comment by klivit** [comment]
<img width="1326" alt="Screenshot 2021-09-16 at 3 48 17 PM" src="https://user-images.githubusercontent.com/77613409/133615635-d5b8a3da-43c7-467e-8cf2-cbed652d2e54.png">

**Comment by Mastaleru** [comment]
not reproducible anymore
