### ISSUE TITLE
[CMO]: Successful completion of scanning (minor)

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#262]
The successful completion sign might be applied in green color.

<img width="1232" alt="Screenshot 2021-09-16 at 3 23 47 PM" src="https://user-images.githubusercontent.com/77613409/133616370-ae43559c-6c6c-4f3b-839d-f92323ae0c81.png">

**Comment by Mastaleru** [comment]
Already fixed a long time ago

**Comment by Mastaleru** [comment]
![image](https://user-images.githubusercontent.com/1469129/159441470-49a6c55f-cbf5-47a6-8960-357782efa8d1.png)
