### ISSUE TITLE
[SPO, COU] Implement refresh data modal when order is updated

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#266]
When the other actor is updating the order and the current actor is on the View Single Order page,  show to him a modal that prompts that a new version of the displayed data is available and add a Refresh button that will reload the current view.

**Comment by abhayprasadnovartis** [comment]
Started working on this.

**Comment by abhayprasadnovartis** [comment]
Created PR for this
