### ISSUE TITLE
[SPO, COU, SPO] Implement refresh data modal when shipment is updated

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#267]
When one of the other actors is updating the shipment and the current actor is on the View Single Shipment page,  show to him a modal that prompts that a new version of the displayed data is available and add a Refresh button that will reload the current view.

**Comment by abhayprasadnovartis** [comment]
Started working on this

**Comment by abhayprasadnovartis** [comment]
Created PR for this
