### ISSUE TITLE
[CMO]: Navigate user to View Single Shipment page after CMO press the button "Prepare Shipment"

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#269]
Now the the CMO is redirect to Dashboard-Orders tab.

Redirect him to the new created shipment page and change the text of the redirecting modal to 
"Shipment initiated, redirecting to View Shipment page"

![image](https://user-images.githubusercontent.com/1469129/133748810-530313e0-0be8-4bab-8f56-25f2e8799b75.png)

**Comment by arijitnv** [comment]
I have raised PR for this issue.
