### ISSUE TITLE
[CMO]: Change Shipment Dashboard icon

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#272]
Please reflect the icon that is used for Shipments

<img width="938" alt="Screenshot 2021-09-19 at 11 05 39 PM" src="https://user-images.githubusercontent.com/77613409/133943740-fe0023c5-938d-4d50-bd49-bc88d447e206.png">

**Comment by arijitnv** [comment]
I am working on this request.
