### ISSUE TITLE
[CMO]: Disable Submit button when cannot be submitted

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#275]
The Submit button should be deactivated when Shipment/Kits are not scanned or not scanned correctly.

<img width="937" alt="Screenshot 2021-09-19 at 11 55 06 PM" src="https://user-images.githubusercontent.com/77613409/133944407-d3755fa3-a0ba-4f1f-83c9-47c752622d71.png">

**Comment by paiusCatalin** [comment]
Fixed within #265. 
Now you cannot go to Summary step if the previous steps are not completed.
