### ISSUE TITLE
[CMO]: Shipment details are doubled

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#276]
The details (framed in red) should not be doubled. 

<img width="982" alt="Screenshot 2021-09-20 at 12 08 42 AM" src="https://user-images.githubusercontent.com/77613409/133944824-a029da67-feaa-400a-88d6-e5f0a16fa723.png">

**Comment by Mastaleru** [comment]
Provided mockups: 
![CMO_Prepare_Shipment-19](https://user-images.githubusercontent.com/1469129/133982731-84ac892b-80d2-4381-9f82-73ad31c09ca4.jpg)

**Comment by Mastaleru** [comment]
I agree with the change with the following comment:
Let's keep Kit Id List in the Kits and remove it from Shipment Details
