### ISSUE TITLE
[SPONSOR]: "Ready for Dispatch" shipment cannot be canceled

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#279]
<img width="1188" alt="Screenshot 2021-09-20 at 1 31 35 AM" src="https://user-images.githubusercontent.com/77613409/133945110-3be16f86-5c9d-407c-b5c0-8d9d53b52d81.png">

**Comment by arispapapro** [comment]
![image](https://user-images.githubusercontent.com/37974010/134190604-c346f916-9391-4696-88fb-e94680dc5028.png)
