### ISSUE TITLE
[COURIER] Refresh View Single Shipment data after scanning the shipment and picking it up (put it In Transit)

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#288]
After clicking on Sign button, everything is happening under the hood #286, the modal is closed, but the View Single Shipment data is not refreshed.

![COU-scan-shipment](https://user-images.githubusercontent.com/1469129/134177520-956042b8-fc20-4c00-99fd-47cb6b0354c8.png)

**Comment by Mastaleru** [comment]
See #299 for screenshots

**Comment by abhayprasadnovartis** [comment]
Started working on this

**Comment by abhayprasadnovartis** [comment]
Created PR for this
