### ISSUE TITLE
[COURIER] Do not show the Scan & Pick-up Shipment button once the Shipment is picked-up and in Transit

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#289]
At this stage only the Edit Shipment button should be visibile. Later, after the first edit, a new button "Scan & Deliver Shipment will appear"
![image](https://user-images.githubusercontent.com/1469129/134180331-f427b590-74bb-4552-b5bb-3410dbda3a87.png)

**Comment by arijitnv** [comment]
I am working on this request

**Comment by arijitnv** [comment]
I have raise the PR for this issue.
