### ISSUE TITLE
[SPO] The order single view is not updated when shipment changes status from In Preparation to Ready for dispatch

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#326]
Steps to reproduce:
Sponsor: Make an order and approve it. Then go to its single view.
CMO: Go to that accepted order and create the shipment from it by pressing the **Prepare Shipment** buttton
CMO: Go to Shipment, scan it prepare for dispatch.

On the sponsor view single order, the  order still can be canceled and Pending Action: is Pending Shipment Preparation

On CMO:
![image](https://user-images.githubusercontent.com/1469129/135082413-b8a056a3-a598-49da-b092-444a99d5cefa.png)

On SPONSOR:
![image](https://user-images.githubusercontent.com/1469129/135082506-c8ded53d-7d62-4f41-a8f4-906843022147.png)

If you go to dashboard and then go to that order again, everything is fine.

**Comment by abhayprasadnovartis** [comment]
Created PR for this
