### ISSUE TITLE
[CMO] Add Try again button when the scanning process fails

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#346]
<img width="1181" alt="Screenshot 2021-09-30 at 10 24 01 AM" src="https://user-images.githubusercontent.com/77613409/135407322-5c92c840-ad3c-4744-9d4b-b217666a35bb.png">

**Comment by klivit** [comment]
"Previous" and "Scan again" serve the same function. Can we remove "Previous" as there is no previous prior to "1 - Scan Shipment" step. Thanks!
 
![Screenshot 2021-11-02 at 5 50 29 PM](https://user-images.githubusercontent.com/77613409/139884267-3d0d3766-c035-4ffc-a787-5e8bea1b1271.png)

**Comment by Mastaleru** [comment]
@klivit 
what is your opinion on the following screen?
![image](https://user-images.githubusercontent.com/1469129/141750157-96f81782-76c6-4335-b508-b97f650b29f4.png)

somehow I'm missing the Previous button now

**Comment by arispapapro** [comment]
@Mastaleru maybe if i add the button in the middle will be better :)
