### ISSUE TITLE
[CMO] [Courier] Remove unnecessary buttons when updating the changes

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#349]
Why do we need two buttons? The status/details should be automatically updated even the use selects "Close" as they are not asked to approve the changes but receive a message when the changes were applied. Hence, we might have just "Close" or "OK".

<img width="1219" alt="Screenshot 2021-09-30 at 10 53 27 AM" src="https://user-images.githubusercontent.com/77613409/135413228-6e65e76d-10b0-41fc-a397-a9e299e485c1.png">

<img width="1214" alt="Screenshot 2021-09-30 at 10 51 27 AM" src="https://user-images.githubusercontent.com/77613409/135413203-0cb4f424-f0be-4027-9463-fed47d45b4fe.png">

**Comment by klivit** [comment]
[Courier] I received this message even when the status was not updated (only comment added).

<img width="1219" alt="Screenshot 2021-09-30 at 11 31 04 AM" src="https://user-images.githubusercontent.com/77613409/135416999-ddd4e13c-9b44-4219-8b57-6c16dfca7e06.png">

**Comment by Mastaleru** [comment]
duplicate with #336.

**Comment by Mastaleru** [comment]
> [Courier] I received this message even when the status was not updated (only comment added).
> 
> <img alt="Screenshot 2021-09-30 at 11 31 04 AM" width="1219" src="https://user-images.githubusercontent.com/77613409/135416999-ddd4e13c-9b44-4219-8b57-6c16dfca7e06.png">

Will extract to new task
