### ISSUE TITLE
[CMO] "In Transit" status should not be available, only "Ready for Dispatch" & "Dispatched"

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#350]
---Shipment (CMO)
In Preparation (blue color of the status)
Canceled (red color of the status) - fringe
Ready for Dispatch (blue color of the status)
Dispatched (green color of the status)

<img width="1218" alt="Screenshot 2021-09-30 at 10 53 59 AM" src="https://user-images.githubusercontent.com/77613409/135414624-6b3b028e-fe22-42d3-976d-5d7d4b05cf4f.png">

**Comment by Mastaleru** [comment]
@klivit I think it should be Dispatched instead of In Transit and to remain green

**Comment by klivit** [comment]
@Mastaleru Yes, here is the outline for all.

---Order (Sponsor, CMO):
Initiated (blue)
Reviewed by CMO (blue)
Reviewed by Sponsor (blue) - fringe
Approved (green)
Canceled (red) - fringe

---Shipment (Sponsor)
In Preparation (blue)
Canceled (red) - fringe
Ready for Dispatch (blue)
In Transit (blue)
Delivered (blue/green) / I prone to have it in blue.
Received (green)

---Shipment (CMO)
In Preparation (blue)
Canceled (red) - fringe
Ready for Dispatch (blue)
Dispatched (green)

---Shipment (Courier)
Ready for Dispatch (blue)
In Transit (blue)
Delivered (green)

---Shipment (Site)
In Transit (blue)
Received (green)

---Kits (Sponsor, Site) - visualization TBD
Available for Assignment (blue)
Assigned (blue)
Dispensed (blue)
Administered (green)
