### ISSUE TITLE
[CMO] View Shipment page is not updating 

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#373]
1.CMO View Shipment page: Shipment with status Ready for dispatch
2.COURIER is picking up the shipment: The CMO is not receiving the update modal:
Reason: The COURIR is using the new shipmentId to notify, and the CMO does not know the new shipmentId created by the COURIER.

**Comment by abhayprasadnovartis** [comment]
Started working on this
