### ISSUE TITLE
[CMO] When "Clear Scan" is clicked on the summary page after scanning the shipment and individual kits, the screen shows Wrong Shipment Code screen 

### ISSUE THREAD

**Issue by ShrGupta017** [PharmaLedger-IMI/csc-workspace-main#401]
Upon Clear scan, the user should view the same screen as seen after Scan Shipment button click:
After this
![image](https://user-images.githubusercontent.com/91278601/136520417-9dce763d-edd8-48f6-b050-6e78d42f193a.png)

We can see this:
![image](https://user-images.githubusercontent.com/91278601/136520496-2e9464c2-1323-4424-acf4-ce57b0ef90e9.png)

But we should see this:
![image](https://user-images.githubusercontent.com/91278601/136520536-4664e8be-6d72-45cd-9084-7b5de987ec75.png)

**Comment by abhayprasadnovartis** [comment]
Clear Scan wrong Shipment Code screen rectified. Created PR for this
