### ISSUE TITLE
[COURIER] Add Actual Temperature Observed when Shipment is Delivered along with Recipient Name 

### ISSUE THREAD

**Issue by ShrGupta017** [PharmaLedger-IMI/csc-workspace-main#412]
![image](https://user-images.githubusercontent.com/91278601/136942853-cc8e93d7-eb6f-49cf-879d-72b3ddda6afc.png)
Add Actual Temperature Observed field with a DropDown
Within Range
Out of Range

**Comment by Mastaleru** [comment]
@ShrGupta017 @klivit where should I put those values after storing them?

**Comment by Mastaleru** [comment]
in which DSU and who should be able to read them?

**Comment by Mastaleru** [comment]
add it in the shipmentTransitDsu as deliveredObservedTemperature

**Comment by Mastaleru** [comment]
@klivit where do you show this data?

**Comment by klivit** [comment]
@Mastaleru The issue lost its actuality. We do not have "Actual temperature observed" now.

**Comment by Mastaleru** [comment]
Feature no longer required
