### ISSUE TITLE
[All actors] Dashboard / Last modified entry should be on the top

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#424]
<img width="1365" alt="Screenshot 2021-10-13 at 12 19 40 PM" src="https://user-images.githubusercontent.com/77613409/137174153-c857b26c-6c11-492a-a380-b60f9d57292b.png">

**Comment by klivit** [comment]
<img width="1439" alt="Screenshot 2021-11-02 at 11 08 41 PM" src="https://user-images.githubusercontent.com/77613409/139952082-df7202c1-a7ea-4e01-86bb-15da201f3610.png">

**Comment by Mastaleru** [comment]
Fixed on 4.11.2021
