### ISSUE TITLE
[Sponsor] Shipments Dashboard

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#427]
Please check the value, which is shown as invalid. 

<img width="1274" alt="Screenshot 2021-10-13 at 3 22 47 PM" src="https://user-images.githubusercontent.com/77613409/137175010-ccb18417-ad81-48fc-a0e7-a96e11f48f75.png">

**Comment by arispapapro** [comment]
getPickupDateTime(scheduledPickupDate) {
    if (scheduledPickupDate) {
      const timestamp = new Date(`${scheduledPickupDate.date} ${scheduledPickupDate.time}`).getTime();
      return momentService(timestamp).format(Commons.DateTimeFormatPattern);
    }

    return '-';
  }

in ShipmentsControllerImp i have to check the if statement if it passes.
