### ISSUE TITLE
[Courier] Shipment details / Adding HS code and master-way bill N is mandatory

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#428]
<img width="1272" alt="Screenshot 2021-10-13 at 3 33 56 PM" src="https://user-images.githubusercontent.com/77613409/137175247-4d7caa1a-4794-40da-998a-06c81f82491a.png">

**Comment by Mastaleru** [comment]
I still can navigate through the stepper buttons 
![image](https://user-images.githubusercontent.com/1469129/137735469-f55c1c08-5d98-424a-862d-a111e238e400.png)

There is an example in the order creation how to also disable stepper buttons while the form is invalid

**Comment by arispapapro** [comment]
I fixed that @Mastaleru
