### ISSUE TITLE
[Courier] Shipment details / Cannot submit the form 

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#430]
<img width="1275" alt="Screenshot 2021-10-13 at 3 43 43 PM" src="https://user-images.githubusercontent.com/77613409/137176164-8049cc03-7dc5-4aa0-9ce5-39979aa77052.png">

**Comment by Mastaleru** [comment]
@arispapapro I saw this problems several times, but I don't know exact the pattern to reproduce it. Ask for Kristina's help for this

**Comment by arispapapro** [comment]
I reproduced it yesterday that was the bug that i told you i had
