### ISSUE TITLE
[Courier] The app does not respond after signing

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#431]
The app does not respond after requesting to sign, meaning that the user cannot continue using the app (but only to re-enter).

<img width="1279" alt="Screenshot 2021-10-13 at 12 38 10 PM" src="https://user-images.githubusercontent.com/77613409/137299616-ec68f31d-8f79-48c8-8d16-046d026d54b2.png">

**Comment by Mastaleru** [comment]
Not reproductible anymore
