### ISSUE TITLE
[Courier] Shipments Dashboard / Missing h&min in "Last Modified"

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#432]
<img width="1260" alt="Screenshot 2021-10-14 at 12 20 42 PM" src="https://user-images.githubusercontent.com/77613409/137302085-8553e529-b199-4fc3-b731-a5c18537a6cf.png">

Please change the label:
Schedule Pickup Date/Time -> Scheduled (ED at the end)

**Comment by klivit** [comment]
I am attaching the current status with the scheduled pickup date/time attribute visualization.

<img width="1173" alt="Screenshot 2021-11-08 at 10 36 15 PM" src="https://user-images.githubusercontent.com/77613409/140815158-877c6566-3ce2-4239-86d2-5b6e34311f98.png">

<img width="1167" alt="Screenshot 2021-11-08 at 10 35 53 PM" src="https://user-images.githubusercontent.com/77613409/140815155-1454e7ef-c001-4f50-b8c4-d61be3948c9d.png">

**Comment by Mastaleru** [comment]
@arijitnv can you check why Scheduled Pickup Date/Time does not have 00:00 for time when it was not selected?
