### ISSUE TITLE
[SITE] Set Kit as Available for Assignment

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#440]
![image](https://user-images.githubusercontent.com/1469129/137885261-4908d90f-e889-447d-ab8e-81765f5ba80a.png)

Please implement them as standalone pages instead of modals

![SITE_Manage_Kit-09](https://user-images.githubusercontent.com/1469129/137616726-e3c5ea51-014d-4d1f-b394-845d80c54dd2.jpg)
![SITE_Manage_Kit-10](https://user-images.githubusercontent.com/1469129/137616730-3fce8756-4c90-4d7e-a60e-336e6fc8619f.jpg)
![SITE_Manage_Kit-11](https://user-images.githubusercontent.com/1469129/137616732-34a3cd80-9ea0-4733-aa29-9b04d202cb4f.jpg)
![SITE_Manage_Kit-12](https://user-images.githubusercontent.com/1469129/137616734-2cab21a8-adb7-4648-88a5-d3f406c9f938.jpg)
![SITE_Manage_Kit-13](https://user-images.githubusercontent.com/1469129/137616737-239f688e-9464-4cf5-bead-5c519a16e67f.jpg)
![SITE_Manage_Kit-14](https://user-images.githubusercontent.com/1469129/137616739-baa4d122-6ef9-484c-96d4-e761e7d92507.jpg)
![SITE_Manage_Kit-15](https://user-images.githubusercontent.com/1469129/137616745-dd8b8a05-af37-4c45-b703-e18fa5fd8843.jpg)

**Comment by abhayprasadnovartis** [comment]
Started working on this
