### ISSUE TITLE
[SITE] Implement View single Kit page

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#448]
Data will be provided based on the kitId from KitsService. Ask @Mastaleru for further details

![SITE_Kit_Received-08](https://user-images.githubusercontent.com/1469129/137769602-4b7a8bfe-1c23-4460-a9bd-be5fcde472b8.jpg)

Please start with UI first

**Comment by Mastaleru** [comment]
example of how to get the required data in order to populate the view: https://github.com/PharmaLedger-IMI/csc-workspace-main/blob/d9cae1268864d48c6e75e2b25db4d8ae7b77a4d0/csc-services/controllers/impl/KitsControllerImpl.js#L86

**Comment by abhayprasadnovartis** [comment]
Created a new Kit page and added functionality to display the Kit data. PR has been created for it
