### ISSUE TITLE
[UI / UX] [CMO-SSApp] Fix View Single order page

### ISSUE THREAD

**Issue by paiusCatalin** [PharmaLedger-IMI/csc-workspace-main#45]
Provided mockup
![CMO_Order-Initiated-04](https://user-images.githubusercontent.com/1469129/127863892-f982f7bf-00a6-4008-a180-bb0bc2a9f192.jpg)

**Comment by Mastaleru** [comment]
Fix the Controllers
![image](https://user-images.githubusercontent.com/1469129/128479217-62d9cb6a-cd0a-410a-b3bd-3de07f28016e.png)

**Comment by paiusCatalin** [comment]
To be handled in Issue #56
