### ISSUE TITLE
[SITE] Implement Dispense Kit

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#450]
after #449

![SITE_Kit_Assigned-18](https://user-images.githubusercontent.com/1469129/137770309-55aa6d57-f4b6-4f60-8a69-8f810ffa2493.jpg)

![SITE_Kit_Dispensed-19](https://user-images.githubusercontent.com/1469129/137770367-4ceaf70a-9194-4666-a87e-34deddf7dc4f.jpg)
![SITE_Kit_Dispensed-20](https://user-images.githubusercontent.com/1469129/137770371-d7228cd2-49d3-4e63-8508-30efc12e65ed.jpg)
![SITE_Kit_Dispensed-21](https://user-images.githubusercontent.com/1469129/137770378-7b78983a-c169-40b1-901b-17b1291807f4.jpg)
![SITE_Kit_Dispensed-22](https://user-images.githubusercontent.com/1469129/137770383-c8f39cb5-7739-424d-8137-3f99c2bcc8dd.jpg)

**Comment by klivit** [comment]
I am closing the task, but @ShrGupta017, we will need to discuss the fields with free text as there is no value to type, for example, dose type, instead of selecting for the list (e.g., lotion, tablet, capsule, etc.).
