### ISSUE TITLE
[SPO] [SITE] [COU] Duplicated "In Transit" status

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#465]
![Screenshot 2021-10-21 at 2 50 03 PM](https://user-images.githubusercontent.com/77613409/138271433-819a74c1-db57-4d51-a76a-b4023beabee8.png)

![Screenshot 2021-10-21 at 1 45 29 PM](https://user-images.githubusercontent.com/77613409/138271439-5f3a9178-fc1e-4ca9-b7cd-77ed14a20d7f.png)

![Screenshot 2021-10-21 at 11 41 18 AM](https://user-images.githubusercontent.com/77613409/138271445-c11ecb2a-5cc5-4b74-a66d-e8f23653936d.png)

**Comment by arispapapro** [comment]
![image](https://user-images.githubusercontent.com/37974010/144826078-d0a5706a-457e-47cc-b338-fc0df166a3d2.png)

**Comment by arispapapro** [comment]
When i am debugging the submit of edit shipment in courier the shipmentDB.status value is this
` {
    "history": [
        {
            "status": "In Preparation",
            "date": 1638784567248
        },
        {
            "status": "Ready For Dispatch",
            "date": 1638784600037
        },
        {
            "status": "Pick-up At Warehouse",
            "date": 1638784637803
        },
        {
            "status": "In Transit",
            "date": 1638784651540
        }
    ],
    "keySSI": "BBudGH6ySHG6GUHN8ogNrTWbxQLMyMsu6gthQCMyhbtjDkAeUdLQkQEvQwSvPB24D6P4WvwVMy3z2NGn2RjTYQjJf",
    "uid": "BBudGH6ySHG6GUHN8ogNrTWbxQLMyMsu6gthQCMyhbtjDkAeUdLQkQEvQwSvPB24D6P4WvwVMy3z2NGn2RjTYQjJf"
}`

**Comment by arispapapro** [comment]
Also before the final storage in the update record function the payload is like that, which also seems ok.
![image](https://user-images.githubusercontent.com/37974010/144828269-45ef23ac-859d-4075-91fa-a14ffb5050a5.png)

**Comment by arispapapro** [comment]
On the other hand when i am fetching all the shipments in sponsor view for example the in the status array there is one more inserted.
![image](https://user-images.githubusercontent.com/37974010/144831110-1166903a-c565-4aa9-9c1a-ccf51dc1504b.png)
