### ISSUE TITLE
[COU] Shipment Details / Mandatory fields

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#469]
We will need to discuss with stakeholders to get some clarity of the requirements for fields. TBD...

![Screenshot 2021-10-21 at 11 18 05 AM](https://user-images.githubusercontent.com/77613409/138283786-001274de-e73b-4f1c-9b94-34a5a9c10834.png)

**Comment by Mastaleru** [comment]
@klivit  any news here? how should we proceed with this task?

**Comment by abhayprasadnovartis** [comment]
Made the fields mandatory. Will create PR

**Comment by Mastaleru** [comment]
mark the fields as being mandatory
