### ISSUE TITLE
SPONSOR - Shipment - Remove Kit ID List(.csv) from Shipment Details

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#513]
the download is already implemented in Kits tab
![image](https://user-images.githubusercontent.com/1469129/139438270-cc907191-d3ad-4c6f-b690-f3bfba77b4ba.png)

**Comment by abhayprasadnovartis** [comment]
Removed Kit ID List(.csv) from Shipment Detail and created PR for this
