### ISSUE TITLE
Check and fix deprecation warning

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#551]
![image](https://user-images.githubusercontent.com/1469129/142829782-6953d0b6-88c9-4364-a30d-813c39200675.png)

**Comment by arispapapro** [comment]
I can't reproduce this error. In my dashboard everything is working ok.

**Comment by Mastaleru** [comment]
Another screenshot from today
![image](https://user-images.githubusercontent.com/1469129/152024114-35be1e23-653d-4c36-a431-5bef5b44c7d1.png)

**Comment by Mastaleru** [comment]
The issue is raised because momentjs does not want to guess the format.
So, you will need to specify the format for conversion.
In TableTempateController in sortingFn 
compA should be 
compA = momentService(a[column], **dateFormat**).valueOf();

To achive this, you have to pass the format in the controller , e.g in orders controller when you are defining default sortingRule
![image](https://user-images.githubusercontent.com/1469129/152027286-d1221daf-d2ce-439e-b2d0-e4ecfcc8564c.png)

you have also to pass the dateFormat.
