### ISSUE TITLE
[SPO] New Order / Change of the label in the wizard

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#557]
Following the same approach, we either add more details to other steps (e.g., add a comment, etc.) or remove one as proposed.

![Screenshot 2021-12-13 at 12 12 09 PM](https://user-images.githubusercontent.com/77613409/145817889-5d116802-6229-4c5a-80ec-0030b585f07d.png)

**Comment by Mastaleru** [comment]
Fixed in https://github.com/PharmaLedger-IMI/csc-workspace-main/commit/3d2e57f4b73b377e8618ba06755b4d9b399354df
