### ISSUE TITLE
[SPO, CMO] The update of the order is available only from Notifications

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#560]
CMO reviewed the order, but the status remained "Initiated" for the Sponsor, as shown below.

![Screenshot 2021-12-13 at 2 53 30 PM](https://user-images.githubusercontent.com/77613409/145820599-22904f09-aeca-4a42-bfbc-563df7cffb86.png)

The sponsor was able to access the latest status of the order accessing from Notifications. Please have a look at the order ID and time (upper right corner). 

![Screenshot 2021-12-13 at 2 53 48 PM](https://user-images.githubusercontent.com/77613409/145820592-5eaba7e8-c85a-4e44-8464-0f16b1ca7365.png)

This bug is from business testing environment.

**Comment by klivit** [comment]
I could not replicate it. Please ignore this issue until I will be able to replicate.

**Comment by Mastaleru** [comment]
No longer relevant while the flow will change soon
