### ISSUE TITLE
[CMO] In preparation / Scan Kits changes

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#565]
![Screenshot 2021-12-13 at 3 57 07 PM](https://user-images.githubusercontent.com/77613409/145826993-ab2cfa04-1f1b-4623-a036-8ae1c2e73770.png)

**Comment by Mastaleru** [comment]
I implemented like this:
![image](https://user-images.githubusercontent.com/1469129/162240119-3a4823c6-818f-42c3-9389-7d8a2759c0a6.png)
