### ISSUE TITLE
[CMO] In preparation -> Ready for dispatch / Changes in labels and their order

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#567]
![Screenshot 2021-12-13 at 4 48 11 PM](https://user-images.githubusercontent.com/77613409/145835108-735e29b7-58be-4661-b5a6-9fa498179445.png)

**Comment by Mastaleru** [comment]
Also Change:
Type->Mode of Transport

Add Volume UoM: 
- Meters
- Feet/inch

**Weight UoM**
-Kg/Tone 

**Weight**

**Destination Address**
•	Country
•	PO box
•	City
•	Street
•	Building 


Conditions:mandatory
