### ISSUE TITLE
Add Shipment entry in SPO and SITE when they receive Shipment entry

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#58]
Once the SPO and SITE receive a message that CMO starts a shipment preparation (#108 ), create a new shipment entry in a dedicate database table ("shipments").

The Shipments Dashboard (UI) will be handled in separated tasks #123, #124

![1_CMO_Dashboard-Shipments-01](https://user-images.githubusercontent.com/1469129/128323613-307b0456-03ea-4f6a-865f-82a1f2749a47.jpg)

**Comment by abhayprasadnovartis** [comment]
Started working on this issue

**Comment by abhayprasadnovartis** [comment]
Created a pull request for this
