### ISSUE TITLE
CMO: Add Prepare Shipment button in single order view

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#59]
When an order is approved the Prepare Shipment functionality should be added
![1_CMO_Order_Prepare_Shipment-27](https://user-images.githubusercontent.com/1469129/128324343-036f0cc4-0861-4b0c-a01e-12fed021ba3e.jpg)

**Comment by abhayprasadnovartis** [comment]
started working on this enhancement

**Comment by abhayprasadnovartis** [comment]
Created PR for this

**Comment by Mastaleru** [comment]
#152 should be implemented in order to prevent bugs by creating multiples shipments from the same order
