### ISSUE TITLE
[CMO] Simplifying preparation of shipment

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#596]
Extra step 1
![Screenshot 2022-02-07 at 11 56 56 AM](https://user-images.githubusercontent.com/77613409/152773298-f6e86f19-5479-43f0-9671-c3088112d86c.png)

Once the CMO clicks "Prepare Shipment", they will continue with the following page (without extra step as above and below):

![Screenshot 2022-02-07 at 11 58 11 AM](https://user-images.githubusercontent.com/77613409/152773315-7fa900bc-0dd3-4792-9341-a827c78fc733.png)

Extra step 2 (it was prior to the screen above). We do not need it.

![Screenshot 2022-02-07 at 12 00 13 PM](https://user-images.githubusercontent.com/77613409/152774722-2186ae88-d75d-4120-ae5a-3c1c6412586c.png)

**Comment by Mastaleru** [comment]
In a real environment with blockchain Prepare shipment will may take a while. That we have a loader. After the shipment is created, mounted and anchored, that modal is needed in order to give a proper feedback to user. Otherwise, user will be confused why navigation is taking so long.
