### ISSUE TITLE
[CMO] Updates and new attributes when preparing shipment

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#597]
The following updates are requested by stakeholder group:

![Screenshot 2022-02-07 at 12 00 59 PM](https://user-images.githubusercontent.com/77613409/152775980-b6e5bf89-9bca-43ac-afe1-b2bd3cc96b3d.png)

The following new attributes are to be added (in bold), remaining the order:
- Courier ID _- to be mandatory_
- Origin
- Mode of Transport [Air, Road, Ocean] _- drop-down, selection_
- Scheduled Pickup Date/Time
- **Volume UoM** [**Meters**, **Feet/inch**] _- drop-down, selection_
- Dimension (Height, Length, Width)
- **Weight UoM** [**Kg**, **Tonne**] _- drop-down, selection_
- **Weight**
- Shipping/Handling Conditions _- to be mandatory_
- Special Instructions
- **Destination Address** (**Country**, **PO box**, **City**, **Street**, **Building**)

**Comment by Mastaleru** [comment]
merged with #567
