### ISSUE TITLE
[COU] Changes in the flow when updating shipment (Pickup -> In Transit)

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#600]
The courier starts picking up with the following view:

![Screenshot 2022-02-07 at 3 20 52 PM](https://user-images.githubusercontent.com/77613409/152795865-38554f51-1590-498f-b389-d0cfb75caa5e.png)

Once the courier click on scan button, the following steps were required. However, they will not remain. 

![Screenshot 2022-02-07 at 1 33 44 PM](https://user-images.githubusercontent.com/77613409/152786201-24bc292c-191f-4cee-8309-55c2acfeb7a4.png)
![Screenshot 2022-02-07 at 1 36 59 PM](https://user-images.githubusercontent.com/77613409/152786211-79e7eaf5-2c18-4d70-ac3e-9e91ce7c7e91.png)

Instead, once clinking "Scan & ...", the following details will have to be added in 4 wizard steps:
1 - Shipment details
2 - Add Documents
3 - Comments
4 - Confirm

![Screenshot 2022-02-07 at 1 55 39 PM](https://user-images.githubusercontent.com/77613409/152783710-1cf84cbb-2b58-423c-b148-16008edfafe5.png)

### 1 - Shipment details
- Shipment ID _- mandatory_
- Master-Way Bill Number 
- HS Code _- mandatory_
- Bill of Landing No. _- text field_ **NEW!**
- Service Type _- text field_ **NEW!**
- Inco Terms _- drop-down_ **NEW!**
•	EXW Works 
•	FCA – Free Carrier 
•	CPT – vCarrier Paid to 
•	CIP – Carrier & Insurance Paid to 
•	DAP - Delivered at place 
•	DDP – Delivered Duty Paid 
•	Other - _If "Other", there should be free-text field to specify_
- Spot/Contract Rates _- text field_ **NEW!**
- Temperature Logger ID _- text field_ **NEW!**

### 2 - Add Documents
![Screenshot 2022-02-07 at 1 56 24 PM](https://user-images.githubusercontent.com/77613409/152785381-b4e18443-965b-4636-ad95-6091b65d1c43.png)

### 3 - Comments
Remain as it is
![Screenshot 2022-02-07 at 1 56 29 PM](https://user-images.githubusercontent.com/77613409/152785721-d169ad52-d253-4327-af42-51003f064aa0.png)

### 4 - Confirm
![Screenshot 2022-02-07 at 1 56 37 PM](https://user-images.githubusercontent.com/77613409/152786009-7a1e203c-e1f8-45d4-ade0-4ea9eb69db01.png)

**Comment by klivit** [comment]
Note: Once Courier starts scanning, the status will be changes from "Ready to Dispatch" to "Pickup at Warehouse"/"Dispatched".

**Comment by Mastaleru** [comment]
@klivit this change still presents interest? or we can close it?
