### ISSUE TITLE
[SITE] Updates when receiving the shipment

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#604]
We keep only "Add a Comment" for now. There is a chance step 2 (2 - Add Details) will be removed.

![Screenshot 2022-02-07 at 6 43 35 PM](https://user-images.githubusercontent.com/77613409/152832944-9a1f282f-051a-4c85-ae5d-16c5c3948334.png)

**Comment by Mastaleru** [comment]
@arispapapro estimation?

**Comment by Mastaleru** [comment]
@arispapapro 
![image](https://user-images.githubusercontent.com/1469129/162388705-349981c6-967e-4b82-b665-af8d7dcb3161.png)

**Comment by Mastaleru** [comment]
![image](https://user-images.githubusercontent.com/1469129/162388988-0908b2b0-d403-437d-bac6-8371fcea91fa.png)

**Comment by Mastaleru** [comment]
reason for reopening?
