### ISSUE TITLE
[COU] Fixing wizard

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#606]
Please adjust wizard style for Courier at the following step:
![Screenshot 2022-02-07 at 5 42 38 PM](https://user-images.githubusercontent.com/77613409/152839893-af4da4f2-4e23-468c-8b3e-655bd36e5b3b.png)

Wizard example
![Screenshot 2022-02-07 at 5 50 02 PM](https://user-images.githubusercontent.com/77613409/152839880-e0c41aa1-a0e5-4268-9b48-03193ac135d5.png)

**Comment by arispapapro** [comment]
This task is implemented. @klivit please close it.
