### ISSUE TITLE
[SITE] Fixing wizard

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#607]
Similar issue #606 

Please adjust wizard style for Site at the following step (receiving shipment):
![Screenshot 2022-02-07 at 6 43 03 PM](https://user-images.githubusercontent.com/77613409/152840208-e910f3a6-1e58-4a30-9af5-f9c065ce120e.png)

Please adjust wizard style for Site at the following step (kits management):
![Screenshot 2022-02-07 at 6 49 39 PM](https://user-images.githubusercontent.com/77613409/152840373-1c9e58e9-e3bc-44cd-9866-1c7ef3ae97d7.png)

Wizard example
![Screenshot 2022-02-07 at 5 50 02 PM](https://user-images.githubusercontent.com/77613409/152840143-0d6ca28b-7825-4ca3-92ae-6e430cc7f6ae.png)

**Comment by arispapapro** [comment]
This task is implemented.
