### ISSUE TITLE
[SITE] Adding pre-step of scanning prior managing kits

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#608]
@Mastaleru Please help to assess feasibility.

When we go to kits under the shipment/order as below, ...
![Screenshot 2022-02-07 at 7 23 30 PM](https://user-images.githubusercontent.com/77613409/152841255-57576034-45bc-4757-9489-a271aba7e367.png)

[...] we see a list of kits as follows. 
![Screenshot 2022-02-07 at 7 23 38 PM](https://user-images.githubusercontent.com/77613409/152841364-064c1c43-04d0-47e7-8148-0b6ed5940193.png)

The kits have no printed ID, only the code to be scanned. Hence, direct selection of the kit to process won't be feasible. The proposal would be to add scan button as shown below to scan any kit in the shipment/order.
![Screenshot 2022-02-07 at 7 23 38 PM](https://user-images.githubusercontent.com/77613409/152842369-2a66359b-391c-471a-b177-365f2ca8fa79.png)

If the kit is found, the user will be directed to the page with this kit.
![Screenshot 2022-02-07 at 7 37 21 PM](https://user-images.githubusercontent.com/77613409/152841805-c08709d9-23d0-4471-90b6-f9a49583655e.png)

Once you confirm, more details will be provided.

**Comment by Mastaleru** [comment]
I agree. I will propose a solution.

**Comment by Mastaleru** [comment]
We should think more about it, while the scanning process of the kit will be doubled, one from the dashboard and one from the Mange Kit...
