### ISSUE TITLE
[SITE] Updates in details when dispensing kit

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#609]
![Screenshot 2022-02-07 at 7 50 52 PM](https://user-images.githubusercontent.com/77613409/152860691-ba316a89-a695-469f-ad70-7c9ab69edbb0.png)

There are more updates as follow.
1. After Dose Type, we need to add new attribute "Dose UoM", a drop-down list with the following options: mL, mg (for now, there are could be updates from stakeholder). Here is the link for all UoM by FDA: https://www.fda.gov/industry/structured-product-labeling-resources/units-measure
2. We had "Kits Storage Condition" in the workflows. I believe we could keep it remaining. As extra (if we have time), we could propose to print it out from the system to be given to a patient as a reminder (if/when valid).

**Comment by Mastaleru** [comment]
@arispapapro estimation?

**Comment by Mastaleru** [comment]
![image](https://user-images.githubusercontent.com/1469129/165281126-4a47296e-1c12-4dcd-9a79-cad5f373590e.png)

**Comment by Mastaleru** [comment]
this is what I have now

**Comment by klivit** [comment]
@arispapapro All elements shall be mandatory.
