### ISSUE TITLE
CMO: Scan Shipment 

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#61]
Once CMO is on the **View Shipment** page it should be able to start scanning kits by pressing **Scan Shipment** button

![CMO_Shipment_In-Preparation-05](https://user-images.githubusercontent.com/1469129/128325205-279e730c-c7c5-4749-8286-e1b18f4814e5.jpg)

**Scan Shipment** button will open a modal and the scan process will work as indicated in the following mockups:

![CMO_Prepare_Shipment-06](https://user-images.githubusercontent.com/1469129/128326272-15f051ed-17c5-48e0-bf5f-0aff8a2edee9.jpg)
![CMO_Prepare_Shipment-07](https://user-images.githubusercontent.com/1469129/128326281-653e6133-fe1c-412f-abda-170e17d49a50.jpg)
![CMO_Prepare_Shipment-08](https://user-images.githubusercontent.com/1469129/128326284-21bb1a64-b2c7-49ed-827b-d4d66b8704e7.jpg)
![CMO_Prepare_Shipment-09](https://user-images.githubusercontent.com/1469129/128326288-b5f0993b-1a3e-4be1-9fdb-8146e492d186.jpg)
![CMO_Prepare_Shipment-10](https://user-images.githubusercontent.com/1469129/128326291-a418ec6a-6e86-4568-afe0-026fdad97073.jpg)
![CMO_Prepare_Shipment-10-25 - 2 2-1a](https://user-images.githubusercontent.com/1469129/128326302-a9f9c271-e6f6-4bb3-9f99-f7a24020b29d.jpg)
![CMO_Prepare_Shipment-11](https://user-images.githubusercontent.com/1469129/128326310-7ab50910-df66-4ec3-b4d6-00334abd13f5.jpg)
![CMO_Prepare_Shipment-12](https://user-images.githubusercontent.com/1469129/128326327-38e89e11-2b38-4982-8970-29bbbc29604f.jpg)
![CMO_Prepare_Shipment-13](https://user-images.githubusercontent.com/1469129/128326340-43c08b2f-0235-4140-8f4e-b0049fc99a7a.jpg)
![CMO_Prepare_Shipment-14](https://user-images.githubusercontent.com/1469129/128326352-94aa2622-55bc-48a4-a31a-1b03c4cbd14d.jpg)
![CMO_Prepare_Shipment-15](https://user-images.githubusercontent.com/1469129/128326360-c950f837-427a-49e6-9522-28e431ecc757.jpg)
![CMO_Prepare_Shipment-15-26 - 2 2-1b](https://user-images.githubusercontent.com/1469129/128326368-f12c3ce5-3e7a-4220-b4fc-2d25b0bfea9d.jpg)
![CMO_Prepare_Shipment-16](https://user-images.githubusercontent.com/1469129/128326381-89902d92-f236-4900-8113-a19d5914ed7a.jpg)
![CMO_Prepare_Shipment-16_1](https://user-images.githubusercontent.com/1469129/128326391-f1d86408-f67d-4b01-b7f3-5fac420c366e.jpg)
![CMO_Prepare_Shipment-16_2 - 2 2-1c](https://user-images.githubusercontent.com/1469129/128326402-40e96a79-5c23-4a9d-9d8f-c0b26cebed30.jpg)
![CMO_Prepare_Shipment-17](https://user-images.githubusercontent.com/1469129/128326415-8ae22311-7d0a-446a-baa3-3c8249441327.jpg)
![CMO_Prepare_Shipment-18](https://user-images.githubusercontent.com/1469129/128326471-9762c488-29e9-46a5-8178-645bc990e488.jpg)
![CMO_Prepare_Shipment-19](https://user-images.githubusercontent.com/1469129/128326486-39dd470d-df4c-4627-bc65-445ed8d2ac6e.jpg)

**Comment by Mastaleru** [comment]
Please rename Confirmation to Summary.

**Comment by klivit** [comment]
More clarifications and updates
1 -- As discussed today, step 3 in Wizard (3 - Scan Shipment) will be excluded. So, after "2 - Scan Kits, we get "3 - Summary".
2 -- During the kit scanning, the user should be provided with info regarding the number of kits scanned (e.g., 1 of 6) to evaluate the remaining workload.
3 -- If the kit scan was not successful (e.g., scanned the wrong kit), the user should have an unlimited number of times to try again.  
4 -- For the MVP, the table "Kit Number - Kit ID" will have one column (Kit ID).

**Comment by Mastaleru** [comment]
To be enhanced in #265
