### ISSUE TITLE
Users DIDs should be displayed in the Order/Shipments/Kits Comments Sections

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#615]
Now only the Role is displayed
It should be [Role][DID]
![image](https://user-images.githubusercontent.com/1469129/155198168-ddea6aaf-9b9b-47cf-af7b-950ae19a8c3f.png)

**Comment by Mastaleru** [comment]
Also  in the confirmation sections like here
![image](https://user-images.githubusercontent.com/1469129/155199258-f1f0d849-46d2-4c15-97df-fe831437da99.png)
and here
![image](https://user-images.githubusercontent.com/1469129/155199357-a89f5406-1cdb-4a98-b5e5-6ee9f1ea0ed6.png)

**Comment by Mastaleru** [comment]
on the shipment comments:
![image](https://user-images.githubusercontent.com/1469129/155199470-290b621e-aa1a-4f0e-af72-dfed6c487723.png)

**Comment by Mastaleru** [comment]
On the CMO page
![image](https://user-images.githubusercontent.com/1469129/171859070-7738bc53-ef80-4715-aba0-fb9b55d94a45.png)

**Comment by arispapapro** [comment]
is this still pending?

**Comment by Mastaleru** [comment]
yes, extracted it in another issue #740

**Comment by arispapapro** [comment]
ok #740 is done.
