### ISSUE TITLE
[CMO] No order is appearing once initiated

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#623]
Tested several times, below I attach the print screens of the issue.

**Attempt 1**
Sponsor initiated the order. 
<img width="1201" alt="Screenshot 2022-02-27 at 1 42 03 PM" src="https://user-images.githubusercontent.com/77613409/155881337-7e48ebc4-2767-433a-9c20-32f477795601.png">

CMO cannot see the order. 
<img width="1202" alt="Screenshot 2022-02-27 at 1 41 42 PM" src="https://user-images.githubusercontent.com/77613409/155881339-2dd51775-334b-4d26-9dfc-75a568a7f34c.png">

**Attempt 2**
Sponsor initiated a new order. 
<img width="1396" alt="Screenshot 2022-02-27 at 1 45 26 PM" src="https://user-images.githubusercontent.com/77613409/155881377-af6c4936-7874-4d3d-9149-d10f62aef1f0.png">

CMO (new account) cannot see the order.
<img width="1397" alt="Screenshot 2022-02-27 at 1 44 51 PM" src="https://user-images.githubusercontent.com/77613409/155881381-f873f3cb-7797-40bd-baaf-d3eddd4eaf95.png">

**Comment by Mastaleru** [comment]
fixed and deployed new release
