### ISSUE TITLE
[COU] No shipment is appearing once initiated

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#624]
Courier does not see the shipments ready for dispatch.

<img width="1397" alt="Screenshot 2022-02-27 at 2 14 06 PM" src="https://user-images.githubusercontent.com/77613409/155881905-4ff8ebdb-98d6-48e2-b31a-484bc9b168fe.png">

<img width="1396" alt="Screenshot 2022-02-27 at 2 14 29 PM" src="https://user-images.githubusercontent.com/77613409/155881912-3cdd4e10-114d-4617-96c7-ec51a5c97edc.png">

Please note that these orders-shipments were created before issue #623 appeared. Once the current issue was discovered, there was an attempt to create a new order and proceed with the full flow, but it didn't work.

**Comment by Mastaleru** [comment]
fixed and deployed new release
