### ISSUE TITLE
[SITE] [SPO] New scenario -- Product Non-Compliant (Damaged or Temperature Excursion) 

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#657]
This scenario happens when the product that was received is damaged or after the check/analysis of the temperature logger, temperature excursion is detected.

The full flow of the fringe:

Fig.1a

![csc non-compliant 2022-04-20](https://user-images.githubusercontent.com/77613409/164170906-cb5c00f2-836a-46b4-b694-10f98b4fb896.png)

Fig. 1b Full Quarantine scenario

![csc quarantine png 2022-04-20](https://user-images.githubusercontent.com/77613409/164171032-0d1a8e1f-f5af-42c8-aae1-77d8a9acf8a3.png)

Note: Product Non-Compliant fringe scenario is applicable to the following statuses: **_Received_**, **_Available for Assignment_**, **_Assigned_**, which means that the product is possible to quarantine with the end of study reason only from the following pages.

Related issue: #692

**_Received_**
After the kit is received, the user can make it available or quarantine it. _(Before it was "Manage Kit" and the kit, after Scan - Ass Details - Sign, would become available for assignment.)_

Fig.2a

![Screenshot 2022-04-14 at 4 09 18 PM](https://user-images.githubusercontent.com/77613409/163397482-a5b66972-4d9e-451b-8d45-574d2b8f01ad.png)

 **_Available for Assignment_**

Fig.2b

![163807899-53a8affe-d86b-4ff1-bad5-02a44035948d](https://user-images.githubusercontent.com/77613409/164177750-8e420ece-f5ea-4fa0-a7d4-969d07074432.png)

**_Assigned_**

Fig.2c

![163811250-2968a381-74dd-4410-8757-9f6adba44a3c](https://user-images.githubusercontent.com/77613409/164172713-20c4f79b-ba65-4a5e-be14-d153670519fd.png)

### Quarantine

Once the damage/temperature excursion is found, the **Site** will quarantine the damaged _kit_ by clicking "Quarantine Kit" button.

Once the damage/temperature excursion is found, the **Site** will scan the damaged _kit_ within the application.

Fig.3
![Screenshot 2022-04-14 at 4 47 48 PM](https://user-images.githubusercontent.com/77613409/163813292-e521bb30-55b3-4fbf-9fa3-d5eb392440bb.png)

Once successfully scanned, **Site** will add the following details through the wizard:
•	Reason [Drop-down list]
        •	Product Damaged
        •	Temperature Excursion

Fig.4
![Screenshot 2022-04-18 at 4 22 51 PM](https://user-images.githubusercontent.com/77613409/163814398-47afdcd5-08f3-4f9b-b86a-db59de829735.png)

Fig.5
![Screenshot 2022-04-18 at 4 29 34 PM](https://user-images.githubusercontent.com/77613409/163815215-29643c96-1fc7-43d6-bf9d-46c3ce36f0fa.png)

Fig.6
![Screenshot 2022-04-18 at 8 48 10 PM](https://user-images.githubusercontent.com/77613409/163850565-c189271f-9157-4016-bffd-c41c6d31abb8.png)

Once submitted, the _kit_ will have _**In Quarantine**_ status.
**Sponsor** will be notified (Message: Kit [#]: Quarantine).

### Pending Destruction

Once **Site** is informed that the _kit_ will be destroyed, they will change the status of the _kit_ to **_Pending Destruction_** by clicking "Request Destruction" button. 

Fig.7
<img width="859" alt="Screenshot 2022-04-18 at 11 41 33 AM" src="https://user-images.githubusercontent.com/77613409/163782302-ed9b4e25-a4cf-4b32-8b5c-7585b6ded9f7.png">

**Sponsor** will be notified (Message: Kit [#]: Pending Destruction).

### Destroyed

Fig.8
<img width="859" alt="Screenshot 2022-04-18 at 11 43 24 AM" src="https://user-images.githubusercontent.com/77613409/163782532-516ee268-a832-45b7-876f-d12c478e8675.png">

Once the _kit_ is about to be destroyed (after clicking "Confirm Destruction"), the **Site** will scan this _kit_ within the application. The the process is in Fig. 3, 4, 6.

Below are the details that shall be entered in step 2 of wizard (Add Details, Fig. 4).

During the destruction procedure, the **Site** adds the following details:
•	Certification of Destruction [Attached document -- Import/Export docs]
•	Destruction Facility [drop-down list with the facilities, e.g., SPO, CMO]
•	Responsible Person ID [to be manually added]
•	Date of Destruction [to be selected from calendar]
•	Destruction Comments

Once submitted, the _kit_ will have _**Destroyed**_ status.
**Sponsor** will be notified (Message: Kit [#]: Destroyed).

### Color coding for fringe statuses & buttons

![colors 2](https://user-images.githubusercontent.com/77613409/163571652-22d5d365-e430-47cd-9a70-6268c41942f7.jpg)

### Icons for fringe buttons

![Picture 1-](https://user-images.githubusercontent.com/77613409/163861639-80bd22eb-b6a2-4489-b4f3-207021f2634f.png)

**Comment by klivit** [comment]
@Mastaleru Let's discuss during the Tue scrum the details and if all the processes are clear. We might involve our UX expert because there are too many "red" buttons/statuses.

**Comment by Mastaleru** [comment]
@klivit it does not make sense to scan again the kit when you want to confirm destruction. kit may not be in the possession of the SITE anymore. I will skip the part of scanning and I will implement it as a standalone page (like dispense page)

**Comment by Mastaleru** [comment]
Certification of Destruction will be hold in another DSU

**Comment by klivit** [comment]
@Mastaleru Great job!
