### ISSUE TITLE
[SITE] [SPO] New scenarios -- End of Study

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#659]
This scenario happens when study has finished, but the _kits_ (unused product) remain. 

The full flow of the fringe:

Fig.1a
![csc end of study  2022-04-20](https://user-images.githubusercontent.com/77613409/164171163-4d547dee-f692-43aa-b626-7e77ae1e48dc.png)

Fig. 1b Full Quarantine scenario
![csc quarantine png 2022-04-20](https://user-images.githubusercontent.com/77613409/164171032-0d1a8e1f-f5af-42c8-aae1-77d8a9acf8a3.png)

The flow will be similar to #657, but the reason at the first step will be the end of the study, instead of temperature excursion/damaged and there will be more details given to the system in the step of pending destruction.

### Quarantine

When the study duration has reached its end, the **Site** will have to destroy (through quarantine) all kits or products left within the kits (those that were not dispensed). 

Note: End of study fringe scenario is applicable to the following statuses: **_Returned_**, **_Assigned_**, **_Available for Assignment_**, which means that the product is possible to quarantine with the end of study reason only from the following pages (see Fig. 2, Fig. 3, Fig. 4).

Fig. 2. Initiating procedure from **_Available for Assignment_**

![163807899-53a8affe-d86b-4ff1-bad5-02a44035948d](https://user-images.githubusercontent.com/77613409/164177617-a20686c6-ab50-4977-b3d5-b01f1d57f78b.png)

Fig. 3. Initiating procedure from **_Assigned_**

![Screenshot 2022-04-18 at 3 53 41 PM](https://user-images.githubusercontent.com/77613409/163811250-2968a381-74dd-4410-8757-9f6adba44a3c.png)

Fig. 4. Initiating procedure from **_Returned_**

![Screenshot 2022-04-18 at 3 34 47 PM](https://user-images.githubusercontent.com/77613409/163809121-df84432d-ce0d-4b9c-a3a3-e621f5ce0218.png)

Once the user has clicked "Quarantine Kit" button (see Fig. 2, Fig. 3, Fig. 4), the **Site** will scan the _kit_ to be quarantined within the application.

Fig. 5.

![Screenshot 2022-04-14 at 4 47 48 PM](https://user-images.githubusercontent.com/77613409/163813408-5da5f974-ce31-4622-989e-3fdd304580fc.png)

Once successfully scanned, **Site** will add the following details through the wizard:
•	Reason [Drop-down list]
        •	End of Study

Fig. 6.

![Screenshot 2022-04-18 at 4 32 37 PM](https://user-images.githubusercontent.com/77613409/163815604-f085ddcb-bbe2-4f18-9eb7-b977687f68b0.png)

Fig. 7.

![Screenshot 2022-04-18 at 4 35 11 PM](https://user-images.githubusercontent.com/77613409/163815898-b16c28d0-ff2f-4278-96ed-758e75782595.png)

Fig. 8.

![Screenshot 2022-04-18 at 4 39 34 PM](https://user-images.githubusercontent.com/77613409/163816452-05dc67a8-d24d-4a6d-ba9b-9cf96c2dffd9.png)

Once submitted, the _kit_ will have _**Quarantine**_ status.
**Sponsor** will be notified (Message: Kit [#]: Quarantine).

### Pending Destruction

Once **Site** is informed that the _kit_ will be destroyed, they will change the status of the _kit_ to **_Pending Destruction_** by clicking "Request Destruction" button. 

Fig.9

<img width="859" alt="Screenshot 2022-04-18 at 11 41 33 AM" src="https://user-images.githubusercontent.com/77613409/163782302-ed9b4e25-a4cf-4b32-8b5c-7585b6ded9f7.png">

The **Site** will scan the _kit_ within the application.

Fig. 10.

![Screenshot 2022-04-18 at 5 04 59 PM](https://user-images.githubusercontent.com/77613409/163819628-c9efdf83-c49e-44e0-96a2-7936e66a4c41.png)

Then, the **Site** will add the following details through the wizard:
•	Consumed dose
•	Dose compliance (% consumed)

Fig. 11.

![Screenshot 2022-04-18 at 8 44 22 PM](https://user-images.githubusercontent.com/77613409/163850117-a08e885c-306d-4f8b-a502-e656d6a7f735.png)

The summary before submitting will differ based on the status prior to quarantining the _kit_  (i.e., **_Returned_**, **_Assigned_**, **_Available for Assignment_**).

Fig. 12. Summary for **_Available for Assignment_** (3 - Submit) 
+ Consumed dose
+ Dose compliance (% consumed)

![Screenshot 2022-04-18 at 9 17 40 PM](https://user-images.githubusercontent.com/77613409/163854755-a404ded7-cba7-4ed2-9c4b-1da62a5d1a0f.png)

Fig. 13. Summary for **_Assigned_** (3 - Submit)
+ Consumed dose
+ Dose compliance (% consumed)

![Screenshot 2022-04-18 at 9 21 07 PM](https://user-images.githubusercontent.com/77613409/163855291-40f0fde5-464b-4af5-a70f-7660413e8e10.png)

Fig. 14. Summary for **_Returned_** (3 - Submit)
+ Consumed dose
+ Dose compliance (% consumed)

![Screenshot 2022-04-18 at 9 32 22 PM](https://user-images.githubusercontent.com/77613409/163856650-37fe73d9-3e10-4c4c-a62e-ff4aad8411e1.png)

Once submitted, the _kit_ will have _**Pending Destruction**_ status.
**Sponsor** will be notified (Message: Kit [#]: Pending Destruction).

### Destroyed

Once the _kit_ is about to be destroyed (after clicking "Confirm Destruction"), the **Site** will scan this _kit_ within the application. The the process is in Fig. 5, 6, 7, 8.

Below are the details that shall be entered in step 2 of wizard (Add Details, Fig. 6).

During the destruction procedure, the **Site** adds the following details:
• Certification of Destruction [Attached document -- Import/Export docs]
• Destruction Facility [drop-down list with the facilities, e.g., SPO, CMO]
• Responsible Person ID [to be manually added]
• Date of Destruction [to be selected from calendar]
• Destruction Comments

Once submitted, the _kit_ will have **_Destroyed_** status.
Sponsor will be notified (Message: Kit [#]: Destroyed).

### Color coding for fringe statuses & buttons

<img width="1271" alt="Screenshot 2022-04-15 at 3 43 01 PM" src="https://user-images.githubusercontent.com/77613409/163805608-fb07b2d8-bfa6-449f-bc81-4307f92628e0.png">

### Icons for fringe buttons

![Picture 1-](https://user-images.githubusercontent.com/77613409/163861520-ac25d003-f89d-4722-8e8a-bdb239c68c2b.png)

**Comment by Mastaleru** [comment]
@klivit when end of study date has come, the site should be permitted to mark kits as available/assigned/dispensed anymore. It should only quarantine the kit with **End of Study** reason.

**Comment by Mastaleru** [comment]
@klivit I propose to keep also the Product Damaged and Temperature Excursion along with End of Study reason.  Why? Because it is possible that a kit to be damaged after the study ends. There may be different logistic processes for the kits that are damaged/temperature excursion and kits that just does not fulfilled their scope because the study ends.

![image](https://user-images.githubusercontent.com/1469129/165279243-e242bd7d-e432-49c0-99a9-e9fdacbc00ba.png)

**Comment by klivit** [comment]
> @klivit I propose to keep also the Product Damaged and Temperature Excursion along with End of Study reason. Why? Because it is possible that a kit to be damaged after the study ends. There may be different logistic processes for the kits that are damaged/temperature excursion and kits that just does not fulfilled their scope because the study ends.
> 
> ![image](https://user-images.githubusercontent.com/1469129/165279243-e242bd7d-e432-49c0-99a9-e9fdacbc00ba.png)

Hi @Mastaleru! Yes, I think we discussed this option, but to have some of the reasons "muted" depending on the status. Let's discuss it again to finalize it when you are back after vacation.

**Comment by klivit** [comment]
@arispapapro 

Based on our discussion today, we re-approach the UI of the longer fringe scenarios (more than one status). The final status is red (only for Canceled, Wrong Delivery Address, **Destroyed**). The rest of the statuses will be orange (**In Quarantine**, **Pending Destruction**, Relabeling Request, Blocked). See the figure below.

![Screenshot 2022-05-05 at 12 27 47 PM](https://user-images.githubusercontent.com/77613409/166914745-c296acd4-563d-4bab-8f73-1ce753763c5b.png)

**Comment by klivit** [comment]
@arispapapro The other half of the scenario is #657

**Comment by klivit** [comment]
<img width="920" alt="Screenshot 2022-05-11 at 10 59 16 AM" src="https://user-images.githubusercontent.com/77613409/167799054-fc615518-2740-48da-88f4-17c09357e320.png">

**Comment by klivit** [comment]
Based on the analysis of all statuses and going through the flows, the issue can be closed and marked as "Done" under issue #657. The reason is the following: once the order is returned (regardless of the end of the study), it will be reconciled. To simplify, we will not add the "Quarantine Kit" button. Once the solution is demonstrated to the stakeholders, we will reassess inconsistencies or minor corrections required.
