### ISSUE TITLE
[SPO] Bug when adding day in the study duration manually

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#673]
Little bug! When we add study duration **manually** (only), the first digit shall be repeated twice. E.g., if I want “14”, I need to enter “114”; valid only for the day (month and year worked as expected). Related issue: #656

<img width="1403" alt="Screenshot 2022-04-11 at 4 06 33 PM" src="https://user-images.githubusercontent.com/77613409/162760658-bd8c1eea-f7fe-48cb-a2c5-e96936a3e01f.png">

**Comment by Mastaleru** [comment]
Could not reproduce this

**Comment by klivit** [comment]
> Could not reproduce this

@Mastaleru I could not reproduce it with the latest deployment as well! I am closing the issue.
