### ISSUE TITLE
[CMO] KitIdDSU not properly read

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#683]
![image](https://user-images.githubusercontent.com/1469129/162977468-8ca03bc9-f2c2-4a86-8d08-f03708dc6087.png)

If the app is refreshed it works as expected

**Comment by klivit** [comment]
The same as #688

**Comment by Mastaleru** [comment]
@arispapapro it can be easily reproduced on the blockchain environment

**Comment by Mastaleru** [comment]
@arispapapro , @klivit , @joaoluis-pdm I'm still reproducing this 
![image](https://user-images.githubusercontent.com/1469129/173055230-b70f23dc-1c70-4499-a123-a7915f8cab04.png)
