### ISSUE TITLE
[CMO] Deactivated button (visually only) when submitting the shipment

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#684]
When close the window ("x" instead of "Ok", see the screen below), "Submit" is deactivated visually (but works).

<img width="1382" alt="Screenshot 2022-04-13 at 9 52 34 PM" src="https://user-images.githubusercontent.com/77613409/163261018-979921b8-6a62-40d1-9585-f7b71941ecd4.png">

<img width="1381" alt="Screenshot 2022-04-13 at 9 53 37 PM" src="https://user-images.githubusercontent.com/77613409/163261002-e91ebd32-0aed-402e-a441-464703d28ac0.png">

**Comment by Mastaleru** [comment]
@Aris the close X button should have the same handler as "Ok" button
