### ISSUE TITLE
[SPO] Manual entry temperature does not work (minor!)

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#687]
When try to enter "-20" manually (or any other temperature with "-"), it corrects to 20 (no "-").

<img width="1265" alt="Screenshot 2022-04-14 at 11 49 39 AM" src="https://user-images.githubusercontent.com/77613409/163349763-a5c56ab6-995c-4a11-b61e-fd7320889c24.png">

**Comment by Mastaleru** [comment]
webcardinal issue:(
