### ISSUE TITLE
[General] Color coding and icons for fringe scenarios & buttons

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#693]
### Epic 1 - Canceled

<img width="418" alt="Screenshot 2022-04-15 at 3 43 11 PM" src="https://user-images.githubusercontent.com/77613409/163572214-9c04ac60-30d1-4cbd-b57e-0a93e2a26482.png">

_The icon is already in place._

### Epic 2 - Wrong Delivery Address

<img width="424" alt="Screenshot 2022-04-15 at 3 43 34 PM" src="https://user-images.githubusercontent.com/77613409/163572181-1e5ead32-d834-4ae1-ae43-7a107966cfdb.png">

_The icon is already in place._

### Epic 3 - In Quarantine / Pending Destruction / Destroyed

<img width="1271" alt="Screenshot 2022-04-15 at 3 43 01 PM" src="https://user-images.githubusercontent.com/77613409/163572231-10c5448c-5b64-439d-813c-3c021d0e3acd.png">

![Picture 1-](https://user-images.githubusercontent.com/77613409/163861773-aa937836-5040-469f-970a-655ee5c8ad7b.png)

### Epic 3 - Relabeling Request / Blocked

<img width="864" alt="Screenshot 2022-04-15 at 3 44 00 PM" src="https://user-images.githubusercontent.com/77613409/163572156-47451b4a-8e0c-4255-836e-393c1c5de2d2.png">

![Picture 1](https://user-images.githubusercontent.com/77613409/163861792-a7afed99-53ec-4d80-9857-fdcdf3951bb0.png)

**Comment by Mastaleru** [comment]
@klivit **Quarantine Kit** and **Request Destruction** buttons will remain pure red because otherwise user will think that the buttons are disabled

**Comment by Mastaleru** [comment]
![image](https://user-images.githubusercontent.com/1469129/165263870-12e908a0-1399-4139-8535-3948af524eea.png)

**Comment by Mastaleru** [comment]
Results:
![image](https://user-images.githubusercontent.com/1469129/165264954-0729fa99-76da-4215-9c20-f09e17213f99.png)

![image](https://user-images.githubusercontent.com/1469129/165265095-d845b144-458e-478f-a803-c3a63a2ea3cb.png)

![image](https://user-images.githubusercontent.com/1469129/165265227-c199eeb5-4655-4289-982b-abf46ca1e8ef.png)

![image](https://user-images.githubusercontent.com/1469129/165265295-784cd0f1-8eec-4372-b8eb-038bb247c848.png)

**Comment by klivit** [comment]
@arispapapro

Based on our discussion today, we re-approach the UI of the longer fringe scenarios (more than one status). The final status is red (Canceled, Wrong Delivery Address, Destroyed). The rest of the statuses will be orange (In Quarantine, Pending Destruction, Relabeling Request, Blocked). See the figure below. 

![Screenshot 2022-05-05 at 12 27 47 PM](https://user-images.githubusercontent.com/77613409/166913793-b62c0095-6873-44b0-9284-c23d5fffe3bf.png)
