### ISSUE TITLE
[COU] UI of fringe scenarios (Epic 1 & Epic 2)

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#697]
To be discussed first. 

"Cancel" button shall be in orange (see the Fig.2) OR be the same style/format as the other fringe scenarios (e.g., order cancelation, see Fig.3).

Fig.1 
<img width="1242" alt="Screenshot 2022-05-04 at 11 24 32 PM" src="https://user-images.githubusercontent.com/77613409/166897406-f2719a53-9b8c-4e3b-a56a-3dec6e526897.png">

Fig.2
<img width="482" alt="Screenshot 2022-05-04 at 11 34 03 PM" src="https://user-images.githubusercontent.com/77613409/166897574-48070bb5-7a63-490f-86d6-9624d5ff46c4.png">

Fig.3
![Screenshot 2022-05-05 at 12 36 24 PM](https://user-images.githubusercontent.com/77613409/166897919-86d74e9c-899d-42be-baf1-4a26129d6ac1.png)

**Comment by Mastaleru** [comment]
@Aris I propose to have the same format as Fig. 3

**Comment by Mastaleru** [comment]
wrong delivery address modal should look like the cancel order modal. Please also change the color of action button (submit) [Confirm and Cancel Order] in our dark green
![image](https://user-images.githubusercontent.com/1469129/170009865-aee37b44-6359-4eec-bfea-d6c427afac8f.png)

**Comment by arispapapro** [comment]
![image](https://user-images.githubusercontent.com/37974010/170460908-f879b9ab-1c9d-47d4-9cf3-3d48e5ac5b90.png)
Cancel Order Modal is like that currently and wrong delivery address is like that:
![image](https://user-images.githubusercontent.com/37974010/170461012-55f7ccce-8b95-46db-a4d2-5bd5250ea26d.png)
which of them should we keep as design?

**Comment by arispapapro** [comment]
I guess the second @Mastaleru @klivit

**Comment by Mastaleru** [comment]
The second one looks great for me
