### ISSUE TITLE
[COU][SITE][SPO] History - Duplicated status

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#699]
The same duplication for three actors - Sponsor, Courier, Site.

<img width="1244" alt="Screenshot 2022-05-04 at 11 47 28 PM" src="https://user-images.githubusercontent.com/77613409/166905652-75e2cd6a-c16b-4cb0-95cc-e315a467546c.png">

**Comment by Mastaleru** [comment]
I could not reproduce it.
SITE:
![image](https://user-images.githubusercontent.com/1469129/168547337-34449903-2b16-45f9-8233-85cac6707b1d.png)

COURIER:
![image](https://user-images.githubusercontent.com/1469129/168547388-2bf9c109-c2c2-4847-b819-103e711656c5.png)

SPONSOR:
![image](https://user-images.githubusercontent.com/1469129/168547425-6dd349e1-098a-4f48-bd06-8faceb66ddc2.png)
