### ISSUE TITLE
COU: Implement View Shipment page

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#71]
After completion of #70 implement **View Shipment** page as indicated in the mockup.

@klivit what kind of attached documents should we keep/show here?  From my understanding there are some shipmentDocuments which will be added later when the shipment will be "In transit".

![COURIER_Shipment-Ready-02](https://user-images.githubusercontent.com/1469129/128349680-2e84e2a2-28a1-441f-928d-f1ce8566a28d.jpg)

**Comment by klivit** [comment]
@arispapapro Any support needed?
