### ISSUE TITLE
Each operation/submission should be wrapped by the UI progress loader.

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#714]
In the development environment it might not be visible where them are missing. @arispapapro  I could guide you through the blockchain environment how to detect the missing loaders

**Comment by arispapapro** [comment]
sure @Mastaleru lets talk about this on scrum today.

**Comment by arispapapro** [comment]
Add a loader here
![image](https://user-images.githubusercontent.com/37974010/169282571-79ed235b-99ef-477e-959d-016e301034e9.png)

**Comment by arispapapro** [comment]
Also to check when i cancel the shipment
