### ISSUE TITLE
[CMO] Two buttons are nearly (look like) one 

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#745]
Attached with different window size

![Screenshot 2022-06-07 at 2 30 58 PM](https://user-images.githubusercontent.com/77613409/172381924-f781872e-a573-4906-ba6f-c7b458e03311.png)

![Screenshot 2022-06-07 at 2 30 51 PM](https://user-images.githubusercontent.com/77613409/172381910-db411473-5809-42a0-bbf9-addb00a85e5d.png)

**Comment by Mastaleru** [comment]
![image](https://user-images.githubusercontent.com/1469129/173548932-bf8ab69f-142b-4ce6-b3c4-041938efa73b.png)

**Comment by Mastaleru** [comment]
in stretched mode

![image](https://user-images.githubusercontent.com/1469129/173549243-4aa61454-28b8-49ab-ac66-e0bbd1f3ea7a.png)
