### ISSUE TITLE
[CMO] Insignificant changes when CMO adding shipment details

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#746]
Please change the order: first Building and then PO Box.

![Screenshot 2022-06-07 at 2 35 08 PM](https://user-images.githubusercontent.com/77613409/172384240-f950996b-2a2e-497b-a255-17b926043819.png)

Please remove "(M)" in "Dimension (M)" (should be just "Dimension").

![Screenshot 2022-06-07 at 2 36 11 PM](https://user-images.githubusercontent.com/77613409/172384255-38dcac72-5465-43ec-bb50-f7155f488760.png)

**Comment by Mastaleru** [comment]
@arispapapro @klivit please also change the view pages. it does not make sense to have the edit & view pages with different orders
