### ISSUE TITLE
[COU] Adding more details while the shipment is In Transit

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#747]
When we click the "Scan & Pick-up Shipment" button, the status automatically (as in the case of **In Preparation**) will change to **Pick-up at Warehouse** (for Sponsor, Site) /  **Dispatched** (for CMO). 

![Screenshot 2022-06-07 at 3 22 48 PM](https://user-images.githubusercontent.com/77613409/172398692-039faef8-bada-4ffc-8590-06a577007f0a.png)

Before, the Courier first added the shipment ID (1 - scan shipment -> 2 - add details (shipment ID) -> 3 - sign) and then continued updating the shipment details. We are slightly improving the procedure by combining these steps (as shown below).

The user will have a 5-step wizard with the following steps:
1 - Scan Shipment
2 - Add Shipment Details
3 - Add Documents
4 - Add Comment
5 - Sign

### 1 - Scan Shipment
![Screenshot 2022-06-07 at 5 38 40 PM](https://user-images.githubusercontent.com/77613409/172408339-368493a1-93a4-456a-817c-ffe566df6b10.png)

**Note:** To be discussed (see figure above)

### 2 - Add Shipment Details

All details to be added:
•      Shipment ID
•      Master-Way Bill Number
•      HS Code [mandatory]
•      Bill of Landing No. [text]
•      Service type [text]
       •      Inco Terms [drop-down]
       •      EXW Works 
       •      Free Carrier - FCA
       •      Carrier Paid to - CPT 
       •      Carrier & Insurance Paid to - CIP 
       •      Delivered at Place - DAP 
       •      Delivered Duty Paid - DDP 
       •      Other 
•      Spot/Contract Rates [text]
•      Temperature Logger ID	 

![Screenshot 2022-06-07 at 5 58 09 PM](https://user-images.githubusercontent.com/77613409/172413102-415ffc97-f170-4f79-9d02-aaaeaf8a5165.png)

### 3 - Add Documents

![Screenshot 2022-06-07 at 6 11 51 PM copy](https://user-images.githubusercontent.com/77613409/172836624-f1eeceff-62d8-4ee4-b498-9360233b19d2.png)you

### 4 - Add Comment

![Screenshot 2022-06-07 at 6 03 41 PM](https://user-images.githubusercontent.com/77613409/172414438-0ce5b936-ea20-4a07-89c6-f62a94cbb512.png)

### 5 - Sign

![Screenshot 2022-06-07 at 6 07 38 PM](https://user-images.githubusercontent.com/77613409/172836999-3419db5b-c27a-466d-9c2e-245edd663a60.png)

Once the Courier clicked "Sign", the status of the shipment will be changed to **In Transit** (from **Pick-up at Warehouse**).

**Comment by Mastaleru** [comment]
@klivit it is totally wrong to change the status of the shipment without performing the logistic scan

**Comment by klivit** [comment]
> @klivit it is totally wrong to change the status of the shipment without performing the logistic scan

@Mastaleru Unfortunately, scanning here has crucial role in minimizing human error (and many related issues). I propose to discuss this issue today to brainstorm on all our options to make it feasible (or modify).

**Comment by klivit** [comment]
We did not merge the steps but keep two stages (1 -- shipment ID + logger ID / 2-- New shipment details for Courier)
