### ISSUE TITLE
COU: Mount new ShipmentTransitDSU

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#75]
Shipment details edited in #74 should be stored in a separate DSU called **shipmentTransitDsu**

Data elements added for the shipment to be transited
•	masterWayBillN [should not be read by CSI]
•	HsCode [should not be read by CSI] 
•	recipientName
•	deliveryDateTime [auto]
•	shipmentId

A message containing the sReadKeySSI of the shipmentTransitDsu should be sent to SPONSOR and SITE.

The elements are added at different stages of the flow: COU can edit multiple times while the shipment is in transit.

------------------------------------------------------------------
TO BE DISCUSED:
According with dsu_types_csc_v6 agreement we have some notes on shipmentDsu and shipmentTransitDsu:
#### shipmentDSU :
   •	scheduledPickupDateTime [should not be read by CSI]
   •	shippingCondition [should not be read by CSI]
#### shipmentTransitDsu:
   •	masterWayBillN [should not be read by CSI]
   •	HsCode [should not be read by CSI]

This cannot be accomplished with one single DSU, therefore 2 more DSUs are needed in order to assure the desired behavior:
**shipmentTransitMetadataDSU** for storing:
  •	scheduledPickupDateTime 
  •	shippingCondition 
**shipmentTransitBillingDSU** for storing:
•	masterWayBillN 
•	HsCode 
 

In this scenario SPONSOR will receive 3 sReadKeySSIs: **shipmentTransitDsu** , **shipmentTransitMetadataDSU** and **shipmentTransitBillingDSU** and SITE only the shipmentTransitDsu.

**Comment by abhayprasadnovartis** [comment]
Started looking into it

**Comment by abhayprasadnovartis** [comment]
Need more inputs from Kristina

**Comment by abhayprasadnovartis** [comment]
Created PR for this

**Comment by Mastaleru** [comment]
To be revaluated after completion of #74
