### ISSUE TITLE
[SITE] Kit destruction can be confirmed avoiding mandatory fields + can't upload any file

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#750]
1. The destruction can be confirmed even if the mandatory details are not filled in.
2. Once trying to upload, no formats are recognized/can be uploaded. 

![Screenshot 2022-06-07 at 7 44 35 PM](https://user-images.githubusercontent.com/77613409/172437792-e9ff44cc-8968-48dc-b518-9803f9890a1d.png)

![Screenshot 2022-06-07 at 7 44 48 PM](https://user-images.githubusercontent.com/77613409/172437801-81f79d5d-3d37-4340-8d6e-8844cd74e38a.png)

**Comment by klivit** [comment]
Point 2 remains (Once trying to upload, no formats are recognized/can be uploaded).

**Comment by klivit** [comment]
Note: Mac issue

**Comment by Mastaleru** [comment]
an issue with the regex ".*" for chrome on mac. tested with "*" and working as expected
