### ISSUE TITLE
[SITE] Kit dispensing process - changing to wizard

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#752]
Current

![Screenshot 2022-06-07 at 8 01 10 PM](https://user-images.githubusercontent.com/77613409/172442958-86a63de5-9cb8-4997-bf4a-6f4d5cedd621.png)

Change

![Screenshot 2022-06-07 at 8 12 54 PM](https://user-images.githubusercontent.com/77613409/172442926-ef428ee3-22fd-49a0-93ab-d049f13baec4.png)

**Comment by klivit** [comment]
Similar issue #749

**Comment by klivit** [comment]
Remains the same

<img width="1269" alt="Screenshot 2022-06-27 at 11 03 36 PM" src="https://user-images.githubusercontent.com/77613409/176026032-283d19a1-f892-4bbb-b9ee-98db7cc58e04.png">

**Comment by Mastaleru** [comment]
@arispapapro any plan to implement this?

**Comment by Mastaleru** [comment]
I cannot scroll
![image](https://user-images.githubusercontent.com/1469129/193790337-4ce7337a-845e-487f-a2dd-a638655a1f47.png)

**Comment by Mastaleru** [comment]
like patientID, visit Id?

**Comment by Mastaleru** [comment]
@arispapapro 
![image](https://user-images.githubusercontent.com/1469129/193807542-80accfb2-e434-46e8-b12b-59d6f5ad77f1.png)

**Comment by Mastaleru** [comment]
@arispapapro perform validation here 
![image](https://user-images.githubusercontent.com/1469129/193812756-f7baa643-ae12-4006-8c35-6bf00e9d4ec9.png)

**Comment by Mastaleru** [comment]
@arispapapro, @klivit, Kristina put in the task 2 buttons : Clear Changes and Submit, but you added Previous and Submit 
![image](https://user-images.githubusercontent.com/1469129/193813375-5de27f64-b4b1-490e-ac0b-7df58a9e0130.png)

**Comment by Mastaleru** [comment]
@arispapapro why is this field duplicated?
![image](https://user-images.githubusercontent.com/1469129/193816642-b1b40152-09f7-42d5-9f0a-f88d259ab615.png)

**Comment by Mastaleru** [comment]
still reopened. https://github.com/PharmaLedger-IMI/csc-workspace-main/pull/819#issuecomment-1298318787

**Comment by Mastaleru** [comment]
Sometimes, I still cannot go further.

formIsInvalid might be wrongly set. @arispapapro check the asynchronous mechanism that may trigger this bug.
![image](https://user-images.githubusercontent.com/1469129/203080225-72fc1e93-4fea-4db5-967d-ccbcbc74adf2.png)
