### ISSUE TITLE
[SPO] Hard refresh is required to get the latest status of kit

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#769]
The kits status is not updated (no pop-up window proposing to update the details), only hard refresh fixes the situation. Once the hard request is done, all is ok. 

![Screenshot 2022-06-14 at 5 37 18 PM](https://user-images.githubusercontent.com/77613409/173605085-6b298792-55a5-4315-89cb-ff143c69f518.png)

![Screenshot 2022-06-14 at 5 37 41 PM](https://user-images.githubusercontent.com/77613409/173605127-0ef6f7f4-d91e-42b2-ba65-58e88bdc1725.png)

**Comment by klivit** [comment]
The same issue as #753

**Comment by Mastaleru** [comment]
fixed

**Comment by klivit** [comment]
The issue remains.

**Comment by Mastaleru** [comment]
should not be the case now, after some opendsu updates
