### ISSUE TITLE
[All actors] Block UI and inform user when a background message processing is performed

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#788]
Add a nice Blockchain loader
Prevent user to refresh the page

**Comment by Mastaleru** [comment]
const onConfirmRefresh = function (event) {
  event.preventDefault();
  return event.returnValue = "Are you sure you want to leave the page?";
}

window.addEventListener("beforeunload", onConfirmRefresh, { capture: true });

**Comment by klivit** [comment]
@Mastaleru  The loader is there and nice, but when I tried to refresh, I was able to without the notification (e.g., are you sure you want to leave, etc.). I am closing the issue, and the loader is added, and overall we will not have any significantly long operations (e.g., process that takes minutes).
