### ISSUE TITLE
SPO: The order creation modal confirmation contains some dummy data regarding the order ID.

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#79]
Please have a look in **NewOrderController** and find how the model is sent to the **orderCreatedModal** template and use it in order to display the orderID.

![Order-creation-ill-inputs](https://user-images.githubusercontent.com/1469129/128467074-a671c6db-48b3-4a9c-aca2-bd17be0f39aa.jpg)

![Order-creation---confirmation](https://user-images.githubusercontent.com/1469129/128467113-4ccbed5b-4a79-4b9f-9282-0bac31d45fe1.jpg)

**Comment by arijitnv** [comment]
I have started working on this issue.

**Comment by arijitnv** [comment]
I have fixed this issue and also pushed the code changes to my fork repository. Kindly review the changes.

**Comment by Mastaleru** [comment]
All good!
