### ISSUE TITLE
[SITE] Make certification of destruction optional

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#791]
Please make certification of destruction field optional.
Site - Destruction Confirmation

<img width="1079" alt="Screenshot 2022-06-30 at 4 01 10 PM" src="https://user-images.githubusercontent.com/77613409/176685208-8af0ad2e-c498-4f64-b42a-293e0710ee42.png">

**Comment by Mastaleru** [comment]
when there is not certificate of destruction added the label should still be there
![image](https://user-images.githubusercontent.com/1469129/187072871-058c267d-c47e-4c0b-a80c-0e30a669dff6.png)

**Comment by klivit** [comment]
@arispapapro There was a relabeling as well, but I did not write it in a clear way. I close the issue.
