### ISSUE TITLE
[SITE] Mute button when action is in progress

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#793]
<img width="1223" alt="Screenshot 2022-06-30 at 4 17 59 PM" src="https://user-images.githubusercontent.com/77613409/176742279-c45d6882-6142-48c9-b384-aa146ba9a8e9.png">
<img width="1228" alt="Screenshot 2022-06-30 at 4 19 07 PM" src="https://user-images.githubusercontent.com/77613409/176742287-9d2f73b6-b53b-4c53-b449-62348d97e997.png">

**Comment by klivit** [comment]
The same applied for the following

![Screenshot 2022-07-14 at 9 52 15 AM](https://user-images.githubusercontent.com/77613409/178920005-0c5cc0aa-0fda-4f8c-8f79-dd55f2d36ee5.png)

To be continued...

**Comment by Mastaleru** [comment]
@klivit please continue adding all the screenshots, while @arispapapro cannot finish his task without them :)

**Comment by arispapapro** [comment]
I have to change the button in the kit page but in all ACTORS ( if needed ) . Mostly SITE , SPONSOR.

**Comment by arispapapro** [comment]
Some of the buttons on the kit is on other pages ( so they have other controllers) i have to disable the butons in the external controllers.

**Comment by arispapapro** [comment]
I should try to find all the navigate to another page actions
