### ISSUE TITLE
[SITE] Three changes/updates in the form when dispensing kit

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#794]
![Screenshot 2022-07-01 at 2 30 29 PM](https://user-images.githubusercontent.com/77613409/176888893-653695d5-e27a-4558-9f9d-b51f0ee93bb7.png)

**Comment by arispapapro** [comment]
Shall i delete this from here too? 
![image](https://user-images.githubusercontent.com/37974010/178954968-7fcc1a5a-ad20-434e-afc2-19d454393352.png)

**Comment by klivit** [comment]
1 - Lagging when added manually
2 - Done
3 - Done

"Kit Storage Condition" is newly added, OK.

**Comment by Mastaleru** [comment]
> 1 - Lagging when added manually 2 - Done 3 - Done
> 
> "Kit Storage Condition" is newly added, OK.

1. We cannot handle this due to an issue in webcardinal.

**Comment by Mastaleru** [comment]
we will not fix #1. manual adding negative inputs

**Comment by Mastaleru** [comment]
we will not fix #1. manual adding negative inputs
