### ISSUE TITLE
SPO: Add the right order ID in the breadcrumb navigation used on View Order page

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#80]
Now the order ID is just a dummy string
![breadcrumb](https://user-images.githubusercontent.com/1469129/128469452-e32dbd65-ca0d-4c03-94ff-1ebc1da2652e.jpg)

**Comment by arijitnv** [comment]
I am currently working on it

**Comment by arijitnv** [comment]
I have fixed this issue. Kindly review the changes.
