### ISSUE TITLE
Investigate why Site wallet fails to insert in enclave the shipment record

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#800]
Steps to reproduce:
1.Mark sure Site is offline
2.Courier is making all the steps from picking up the shipment until the deliver
3.Log in in SITE
4. In the console you will find the error

**Comment by paiusCatalin** [comment]
This issue is related to openDSU and can be reproduced also on the other actors.
The messages are being processed in reversed order, but from API-hub.
After a fix on openDSU is provided, I will resume the investigation.
