### ISSUE TITLE
Temperature logger id appears before the shipment is picked up

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#807]
![image](https://user-images.githubusercontent.com/1469129/187066866-d6701608-698d-4bad-b3e2-221365d060a0.png)

**Comment by arispapapro** [comment]
![image](https://user-images.githubusercontent.com/37974010/187411950-d13941fe-df3e-4ce8-80c3-f141cdf4edef.png)

**Comment by arispapapro** [comment]
![image](https://user-images.githubusercontent.com/37974010/187412049-7cc40e86-8baf-4cd7-9b55-09e95c67c640.png)
