### ISSUE TITLE
Wrong Pending Action when an order has status "Initiated"

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#81]
When an order has status **Initiated** the Pending Action should be "Pending Review by CMO"

![pendingActions](https://user-images.githubusercontent.com/1469129/128470954-4e7c34bb-e2f2-48dd-bb48-eb90c156c5d9.jpg)

Provided mockup:

![SPONSOR_Order-Initiated-v1_Accordion-17](https://user-images.githubusercontent.com/1469129/128471048-6a2d1330-6ea4-48b7-ad11-8b77c03cc7ce.jpg)

**Comment by abhayprasadnovartis** [comment]
Started looking into it.

**Comment by abhayprasadnovartis** [comment]
Pending action corrected and created a pull request.

**Comment by Mastaleru** [comment]
Thank you. But what happens if the order is accepted or canceled? What will be the status? If an order has status "Canceled"
pending action should be "There are not further pending actions". 
If an order is "Approved" the pending action should be **Pending Shipment Preparation**

**Comment by abhayprasadnovartis** [comment]
Thank you for providing more inputs on this. Will make changes accordingly.

**Comment by abhayprasadnovartis** [comment]
Pending action corrected for cancelled, approved and pending review status.
Pull request has been created.
