### ISSUE TITLE
Investigate why shipmentscomments failed to be mounted

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#810]
![image](https://user-images.githubusercontent.com/1469129/187070067-20a48278-2f9b-4e0b-92a1-eadb0cefe9fa.png)

**Comment by Mastaleru** [comment]
may be related to issue #808

**Comment by paiusCatalin** [comment]
Fixed within #808

**Comment by arispapapro** [comment]
@paiusCatalin Cool.
