### ISSUE TITLE
[SITE] Comment upon receiving from Site appears as added by Courier (replicated)

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#828]
Site adds a comment.

![Screenshot 2022-11-23 at 3 15 50 PM](https://user-images.githubusercontent.com/77613409/203556651-c59a8dd3-3fed-4651-96d8-ec72f5461457.png)

The comment is shown as it would be given by the Courier.

![Screenshot 2022-11-23 at 3 17 08 PM](https://user-images.githubusercontent.com/77613409/203557170-b0921bf0-4fca-4359-a171-b39a7a5ab247.png)

**Comment by Mastaleru** [comment]
![image](https://user-images.githubusercontent.com/1469129/203742610-cbba68d5-395c-4788-b441-25902bd53331.png)
