### ISSUE TITLE
[SITE] Can't dispense the kit - Blocked flow

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#829]
![Screenshot 2022-11-23 at 3 35 02 PM](https://user-images.githubusercontent.com/77613409/203561285-c4a9265e-9468-4e44-a1cf-8729773a4312.png)

**Comment by klivit** [comment]
Related issue #794

**Comment by Mastaleru** [comment]
next button is disabled when not fields are filled
![image](https://user-images.githubusercontent.com/1469129/203761352-a87589d8-9db2-4041-89b8-39016379d4e7.png)

next button is enabled when fields are filled
![image](https://user-images.githubusercontent.com/1469129/203761556-0e67d827-1001-4cb2-a6bc-cee781329288.png)
