### ISSUE TITLE
SITE: Refactor Dashboard/landing page to have the same code style with CMO dashboard UI

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#83]
CMO Dashboard UI enhancements are completed and it's pages and templates could be used as an example for the SITE dashboard. Please use the same html files structure  with the same layout and elements hierarchy on order to have a CSS rule matching with the existing theme.

You should not write additional CSS code for this task.

Provided mockup:
![1_SITE_Dashboard-Orders-01](https://user-images.githubusercontent.com/1469129/128503182-98bcd0bc-7bd9-4eb8-8987-2778cd298a7c.jpg)

**Comment by arijitnv** [comment]
I have pulled out the latest changes but couldn't able to see the modification in the UI dashboard.

**Comment by arijitnv** [comment]
I am able to see the changes in CMO dashboard now and currently I am working on this enhancement.

**Comment by arijitnv** [comment]
I have modified the whole UI for Site and also pushed the latest changes. Kindly review and let me know for any concern.

**Comment by Mastaleru** [comment]
The html files were 100% copy-pasted from cmo-ssapp. As you know, there are differences between CMO and SITE, but setting  `const ACTOR = cscServices.constants.Roles.Site;`  in app-config.js is not enough. There are some differences also in html files. You have to identify which elements are required in SITE and copy only those elements. Meanwhile your PR is closed without merge.
