### ISSUE TITLE
SITE: Refactor Notifications page to have the same code style with CMO Notifications UI

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#84]
CMO Notifications UI page enhancements are completed and it's pages and templates could be used as an example for the SITE Notifications. Please use the same html files structure with the same layout and elements hierarchy on order to have a CSS rule matching with the existing theme.

You should not write additional CSS code for this task.

Provided mockup:
![SITE_Notifications-258](https://user-images.githubusercontent.com/1469129/128503959-66499498-340d-4d10-aca3-80326a578b99.jpg)

**Comment by arijitnv** [comment]
I have modified the notification UI for Site. Kindly review the changes and merger it with the main branch.

**Comment by Mastaleru** [comment]
The html files were 100% copy-pasted from cmo-ssapp. As you know, there are differences between CMO and SITE, but setting  `const ACTOR = cscServices.constants.Roles.Site;`  in app-config.js is not enough. There are some differences also in html files. You have to identify which elements are required in SITE and copy only those elements. Meanwhile your PR is closed without merge.

**Comment by arijitnv** [comment]
I have refactored the notification page along with the history modal for SITE.
