### ISSUE TITLE
SITE: Refactor View Order page to have the same code style with CMO View Order UI

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#85]
CMO Notifications UI page enhancements are completed and it's pages and templates could be used as an example for the SITE Notifications. Please use the same html files structure with the same layout and elements hierarchy on order to have a CSS rule matching with the existing theme.

You should not write additional CSS code for this task.

![SITE_Order-Initiated-04](https://user-images.githubusercontent.com/1469129/128505975-e59759af-6a0c-4ab3-be24-0ef64f9bb432.jpg)

**Comment by arijitnv** [comment]
I am working on this request.

**Comment by arijitnv** [comment]
I have removed the 'Attachment' section and the 'Review' button in the view order dashboard for Site and also cleaned the folder by deleting two unnecessary files.. Kindly review and pull the latest changes.

**Comment by Mastaleru** [comment]
Please don't combine multiple tasks in one single PR.

**Comment by Mastaleru** [comment]
Please fix the History Modal 
![image](https://user-images.githubusercontent.com/1469129/129325483-949926c1-d9f4-454c-8b30-97b38baef6ba.png)
