### ISSUE TITLE
SPO: Misleading order details in the Orders dashboard table

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#89]
Some order details are not properly displayed according with the table header.
![wrong-order](https://user-images.githubusercontent.com/1469129/128530387-02f589be-dfb3-43ae-aa06-3da9d9fcb7bd.jpg)

**Comment by arijitnv** [comment]
I am currently working on this issue. Kindly change the status to 'In Progress'.

**Comment by arijitnv** [comment]
I have fixed this issue. I have rearranged the id's in the table-template.html in all ssapps.
